### ISSUE TITLE
kf5-kjs build failed

### ISSUE THREAD

**Issue by pegasus87** [KDE-mac/homebrew-kde#101]
Hi,
I'm trying to install kmymoney and therefore the dependency kjs is required. But at this point the build process stops with an error.

`==>
 Installing haraldf/kf5/kf5-kmymoney dependency: haraldf/kf5/kf5-kjs
==> Downloading http://download.kde.org/stable/frameworks/5.32/portingAids/kjs-5.32.0.tar.xz
Already downloaded: /Users/****/Library/Caches/Homebrew/kf5-kjs-5.32.0.tar.xz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kjs/5.32.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=O
==> make install

Last 15 lines from /Users/****/Library/Logs/Homebrew/kf5-kjs/02.make:
                           ^~~~~~~~~~~~~~
/tmp/kf5-kjs-20170423-29699-1o68e2/kjs-5.32.0/src/kjs/makenodes.h:307:23: note: candidate function not viable: no known conversion from 'std::__1::nullptr_t' to 'const KJS::Identifier' for 3rd argument
static StatementNode *makeImportNode(PackageNameNode *n,
                      ^
grammar.y:876:28: error: no matching function for call to 'makeImportNode'
            (yyval.stat) = makeImportNode((yyvsp[(2) - (3)].pkgn), false, nullptr);
                           ^~~~~~~~~~~~~~
/tmp/kf5-kjs-20170423-29699-1o68e2/kjs-5.32.0/src/kjs/makenodes.h:307:23: note: candidate function not viable: no known conversion from 'std::__1::nullptr_t' to 'const KJS::Identifier' for 3rd argument
static StatementNode *makeImportNode(PackageNameNode *n,
                      ^

12 errors generated.
make[2]: *** [src/kjs/CMakeFiles/KF5JS.dir/grammar.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/kjs/CMakeFiles/KF5JS.dir/all] Error 2
make: *** [all] Error 2`

I installed dbus and qt5 before.
For me, it seems to be a problem in the code... Any ideas how to fix that? Maybe we have to wait for an update to kf 5.33

**Comment by forivall** [comment]
Same. I put the error log in a gist so it's readable: https://gist.github.com/forivall/457d1fcf4283673d6cce209824e3fc8c

**Comment by pegasus87** [comment]
@forivall Thanks!

**Comment by yurikoles** [comment]
@pegasus87 and @forivall, you are doing it wrong. The proper way is `brew gist-logs kf5-kjs` https://gist.github.com/yurikoles/b3cf2672f9fafa3d66efa7236f25d66a
