### ISSUE TITLE
Homebrew Tap

### ISSUE THREAD

**Issue by industrie13** [KDE-mac/homebrew-kde#11]
just a hint, the homebrew tap in the README.md needs to be

```
`brew --prefix`/Library/Taps/haraldf/homebrew-kf5/tools/install.sh --HEAD
```

Currently it is just 

```
haraldf-kf5
```

By the way,

```
`brew --prefix`/Library/Taps/haraldf/homebrew-kf5/tools/install.sh
```

installs fine while installing the gitversion immediately produces an error 

```
`brew --prefix`/Library/Taps/haraldf/homebrew-kf5/tools/install.sh --HEAD
==> Cloning git://anongit.kde.org/extra-cmake-modules
Updating /Library/Caches/Homebrew/kf5-extra-cmake-modules--git
==> Patching
patching file kde-modules/KDEInstallDirs.cmake
Hunk #1 FAILED at 143.
1 out of 1 hunk FAILED -- saving rejects to file kde-modules/KDEInstallDirs.cmake.rej
Error: Applying DATA patch failed
```

**Comment by pasnox** [comment]
`brew --prefix`/Library/Taps/haraldf/homebrew-kf5/tools/install.sh is still not working correctly (it looks for rb files which are out of this directory).
I do used:
cd `brew --prefix`/Library/Taps/haraldf/homebrew-kf5 && tools/install.sh (or cd `brew --prefix`/Library/Taps/haraldf/homebrew-kf5 && tools/install.sh --HEAD)
The HEAD variant give errors emmediatly - ECM library is not found.
