### ISSUE TITLE
Okular crashes on start

### ISSUE THREAD

**Issue by bmihaila** [KDE-mac/homebrew-kde#114]
Hi

Installed Okular from https://github.com/haraldF/homebrew-kf5/commit/a7e600f8b2b5be414a66eeb4de711bfb49cf7f98
Installation succeeds fine but starting Okular gives this error:

<img width="574" alt="screen shot 2017-05-26 at 13 55 42" src="https://cloud.githubusercontent.com/assets/2682197/26492170/842f28ec-421b-11e7-9dca-8259c59e65ba.png">

running it from the commandline gives more hints:
```
/Applications/KDE/okular.app/Contents/MacOS/  
$ ./okular
cannot find .rc file "shell.rc" for component "okular"
```

**Comment by xieyuheng** [comment]
I meet the same issue.

**Comment by xieyuheng** [comment]
I did ::
'''
export QT_PLUGIN_PATH=$QT_PLUGIN_PATH:/usr/local/Cellar/kf5-okular/17.08.0/lib/plugins
'''

then okular can start,
but it can not open pdf file ::
'''
bash-3.2$ ./okular
cannot find .rc file "shell.rc" for component "okular"
Unable to open DrawingTools XML definition
Unable to open AnnotatingTools XML definition
Error: standard icon theme "hicolor" not found!
cannot find .rc file "part.rc" for component "okular"
cannot find .rc file "shell.rc" for component "okular"
Error: standard icon theme "hicolor" not found!
org.kde.okular.core: No plugin for mimetype '"application/pdf"'.

'''

**Comment by pat-s** [comment]
I also confirm the issue.

**Comment by sl1pkn07** [comment]
done in my branch

the problem is need symlink `/usr/local/share/okular` to `~/Library/"Applications Support"` and, the most important, set `QT_PLUGIN_PATH=$(brew --prefix)/lib/qt5/plugins` in the environment. 

this last only work if you launch the program under console. into the desktop. need run
~~~bash
/usr/libexec/PlistBuddy -c Add :LSEnvironment:QT_PLUGIN_PATH string "$(brew --prefix/lib/qt5/plugins\" "$(brew --prefix okular)/bin/okular.app/Contents/Info.plist"
~~~

for add that environment into the application

greetings

**Comment by sl1pkn07** [comment]
done in master

can you confirm if is fixed, @bmihaila ?

**Comment by bmihaila** [comment]
Hi and  thanks for the fixes. Here is how things look now:

```
$ brew update
$ brew uninstall --force kf5-okular
$ brew install okular
==> Installing okular from kde-mac/kde
==> Installing dependencies for kde-mac/kde/okular: cmake, KDE-mac/kde/kf5-extra-cmake-modules, doxygen, libtool, graphviz, KDE-mac/kde/kf5-ki18n, libxml2, libxslt, bzip2, KDE-mac/kde/kf5-karchive, KDE-mac/kde/kf5-kdoctools, qca, little-cms2, ghostscript, libspectre, djvulibre, openjpeg, poppler, KDE-mac/kde/kf5-kconfig, KDE-mac/kde/kf5-kcoreaddons, KDE-mac/kde/kf5-kwindowsystem, KDE-mac/kde/kf5-kactivities, KDE-mac/kde/kf5-kjs, flex, KDE-mac/kde/kf5-solid, KDE-mac/kde/kf5-kcrash, dbus, KDE-mac/kde/kf5-kdbusaddons, KDE-mac/kde/kf5-kservice, KDE-mac/kde/kf5-kglobalaccel, KDE-mac/kde/kf5-kwidgetsaddons, KDE-mac/kde/kf5-kcompletion, gpgme, KDE-mac/kde/kf5-kauth, gperf, KDE-mac/kde/kf5-kcodecs, KDE-mac/kde/kf5-kguiaddons, KDE-mac/kde/kf5-kconfigwidgets, KDE-mac/kde/kf5-kitemviews, KDE-mac/kde/kf5-kiconthemes, hunspell, KDE-mac/kde/kf5-sonnet, KDE-mac/kde/kf5-ktextwidgets, KDE-mac/kde/kf5-attica, KDE-mac/kde/kf5-kxmlgui, KDE-mac/kde/kf5-kbookmarks, KDE-mac/kde/kf5-kjobwidgets, KDE-mac/kde/phonon, KDE-mac/kde/kf5-knotifications, KDE-mac/kde/kf5-kwallet, KDE-mac/kde/kf5-kio, KDE-mac/kde/kf5-kparts, KDE-mac/kde/kf5-kpty, KDE-mac/kde/kf5-threadweaver, exiv2, KDE-mac/kde/libkexiv2
==> Installing kde-mac/kde/okular dependency: cmake
[...]

==> Caveats
[done those]

$ open -a okular
[fails with same error dialog as reported in this bug]

$ /usr/local/opt/okular/bin/okular.app/Contents/MacOS/okular
[same here]

$ export QT_PLUGIN_PATH=$($(brew --prefix qt)/bin/qtpaths --plugin-dir):$(brew --prefix)/lib/qt5/plugins
$ /usr/local/opt/okular/bin/okular.app/Contents/MacOS/okular
cannot find .rc file "shell.rc" for component "okular"
cannot find .rc file "part.rc" for component "okular"
cannot find .rc file "shell.rc" for component "okular"
objc[41430]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb19e4a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1121cccd8). One of the two will be used. Which one is undefined.

[works! see screenshot below with a pdf]
```
<img width="803" alt="screen shot 2017-11-17 at 17 06 07" src="https://user-images.githubusercontent.com/2682197/32953716-b548b86c-cbb9-11e7-944b-3d13d574727a.png">

So it seems that it only works from the commandline and with the `QT_PLUGIN_PATH` variable set. Might it be that plistbuddy failed, see this:
```
$ /usr/libexec/PlistBuddy -c Add :LSEnvironment:QT_PLUGIN_PATH string "/usr/local/Cellar/qt/5.9.2/plugins:/usr/local/lib/qt5/plugins" /usr/local/Cellar/okular/17.08.3 
Unrecognized Type:
```

Last but not least, seems that Okular still misses some crucial `.rc` files for its UI and the settings for the application cannot be found from the menu. Any ideas on how to fix those?

Thanks
Bogdan

**Comment by bmihaila** [comment]
Ok, this should be the correct `PlistBuddy` command:
```
$ /usr/libexec/PlistBuddy -c 'Add :LSEnvironment:QT_PLUGIN_PATH string "/usr/local/Cellar/qt/5.9.2/plugins:/usr/local/lib/qt5/plugins"' $(brew --prefix okular)/bin/okular.app/Contents/Info.plist
```
after that, it works to open Okular:
```
open -a okular
[success!]
```

**Comment by sl1pkn07** [comment]
Yep, my fail

Also i think spoted a typo, if you see the content of the Info.plist, the string on that variable is splitted in two lines. Should be only one.

**Comment by bmihaila** [comment]
Hmm.. for some reason the `plistbuddy` did not add something to the `Info.plist`:
```
$ /usr/libexec/PlistBuddy -c 'Print' /usr/local/Cellar/okular/17.08.3/bin/okular.app/Contents/Info.plist                                                     ⏲ 17:38:51
Dict {
    CFBundleName = 
    CFBundleIdentifier = 
    CFBundleLongVersionString = 
    CFBundleInfoDictionaryVersion = 6.0
    CFBundleVersion = 
    CFBundleExecutable = okular
    CFBundleGetInfoString = 
    CFBundlePackageType = APPL
    CFBundleIconFile = okular_SRCS.icns
    CFBundleSignature = ????
    CSResourcesFileMapped = true
    CFBundleDevelopmentRegion = English
    NSHumanReadableCopyright = 
    CFBundleShortVersionString = 
}
```

**Comment by bmihaila** [comment]
Seems to have been about file permissions, file was not writeable. Got is now, so that it looks like this:
```
$ /usr/libexec/PlistBuddy -c 'Print' /usr/local/Cellar/okular/17.08.3/bin/okular.app/Contents/Info.plist                                                     ⏲ 17:41:39
Dict {
    CFBundleName = 
    CFBundleIdentifier = 
    CFBundleLongVersionString = 
    CFBundleInfoDictionaryVersion = 6.0
    CFBundleVersion = 
    CFBundleExecutable = okular
    CFBundleGetInfoString = 
    CFBundlePackageType = APPL
    CFBundleIconFile = okular_SRCS.icns
    CFBundleSignature = ????
    CSResourcesFileMapped = true
    LSEnvironment = Dict {
        QT_PLUGIN_PATH = /usr/local/Cellar/qt/5.9.2/plugins:/usr/local/lib/qt5/plugins
    }
    CFBundleDevelopmentRegion = English
    NSHumanReadableCopyright = 
    CFBundleShortVersionString = 
}
```

However, Okular still does not start. Same error.

**Comment by sl1pkn07** [comment]
the caveats about Applications Support part is done?

**Comment by bmihaila** [comment]
Hi

Yeah, have done the caveats for Okular and now doing the ones for `KDE-mac/kde/kf5-extra-cmake-modules` as those are the only ones there were besides Okular. Guess you meant those with `frameworks`.

However, there is a problem with this:
```
$ ln -sf "$(brew --prefix)/share/kxmlgui5" ~/Library/"Application Support"              
ln: /Users/[me]/Library/Application Support/kxmlgui5: Operation not permitted
```
That directory exists and has plenty of stuff from other programs already:
```
$ ls ~/Library/Application\ Support/kxmlgui5
kate/         katefiletree/ katepart/     kateproject/  katesearch/   katesnippets/ katexmltools/ okteta/       tabswitcher/  textfilter/
```
Would not want to delete or overwrite it.
Seems also that above link caveat would point to Okular only?
```
$ ls /usr/local/share/kxmlgui5
/usr/local/share/kxmlgui5@ -> ../Cellar/okular/17.08.3/share/kxmlgui5
```
Guess that isn't what it should be?

**Comment by sl1pkn07** [comment]
no,  you need keep that. because that symlink is need by other kde applications

if you have that sysmlink, and with that contets, then the symlink is done

**Comment by bmihaila** [comment]
I think it is only about that plist file because it starts fine from cli when `QT_PLUGIN_PATH` is set. But does not start without that env var. So I'll try to find out why it cannot read it from the plist file or why it does not find that file.

Thanks a lot so far.
Any ideas about those missing `.rc` files? Or are they found in your installation?

**Comment by sl1pkn07** [comment]
yep. i have. 

but i see something weird in you comment posted above

https://github.com/KDE-mac/homebrew-kde/issues/114#issuecomment-345287783

i can't found the folder okular into the kxmlgui5 dir

```
└───╼  \ls /usr/local/share/kxmlgui5
gvpart              kmm_csvexport       kmm_icalendarexport kmm_qifexport       kmm_weboob          konversation        okteta              okular
gwenview            kmm_csvimport       kmm_printcheck      kmm_qifimport       kompare             ktorrent            oktetapart
```
are you sure the installation of okular is all done?. seems failed in brew link

please run brew doctor

**Comment by bmihaila** [comment]
Hi again

Ok, got it running after quite some cleanup. It was not so much about `brew doctor` hints but about uninstalling most of the old `kf5-*` packages and removing stale dirs, fixing brew errors etc. After all that cleanup and a fresh reinstall of okular and its dependencies it finally runs! There were for sure plenty of wrong symlinks :) somewhere. Some things still:
```
$ ls /usr/local/share/kxmlgui5
okteta/     oktetapart/ okular@

$ open -a okular
[works! but needed below bugifx]
```

If you look at current /master of the build formula https://github.com/KDE-mac/homebrew-kde/blob/master/okular.rb#L53 there is a typo and you use `kdevelop` instead of `okular` there. Fixing that manually does the deal. But as of that bug, Okular won't of course work if installed from master. Please fix and thanks for everything else. I'll close this bug when above line is fixed as that will solve this issue.

**Comment by sl1pkn07** [comment]
OUCH!

yep. my fault ><

done

**Comment by bmihaila** [comment]
Great, thanks 👍
