### ISSUE TITLE
kf5-kcoreaddons doesn't register in include, lib, etc.

### ISSUE THREAD

**Issue by poke1024** [KDE-mac/homebrew-kde#139]
Whereas `kf5-karchive` and most other packages register themselves in homebrew's include, lib and bin directories, `kf5-kcoreaddons` doesn't. I'm not sure why this is and how to fix this.

The manual way to fix this is to add `ln`s:

```
ln -s $HOMEBREW/Cellar/kf5-kcoreaddons/5.38.0/include/KF5/KCoreAddons $HOMEBREW/include/KF5
ln -s $HOMEBREW/Cellar/kf5-kcoreaddons/5.38.0/include/KF5/kcoreaddons_version.h $HOMEBREW/include/KF5

ln -s $HOMEBREW/Cellar/kf5-kcoreaddons/5.38.0/bin/desktoptojson $HOMEBREW/bin 

ln -s $HOMEBREW/Cellar/kf5-kcoreaddons/5.38.0/lib/cmake/KF5CoreAddons $HOMEBREW/lib/cmake 
ln -s $HOMEBREW/Cellar/kf5-kcoreaddons/5.38.0/lib/libKF5CoreAddons.5.38.0.dylib $HOMEBREW/lib 
```

If I knew where to look, I'd do a PR but I don't understand how this is set up in the `rb` files.

**Comment by franklinyu** [comment]
That's weird, because all these 5 symbolic link exist in my machine… Have you tried `brew link kf5-kcoreaddons`?

**Comment by franklinyu** [comment]
Try uninstall all versions of such formula, then install fresh. Worked for me. Homebrew didn't create new symbolic link to `opt` when upgrading.

**Comment by sl1pkn07** [comment]
@poke1024 wit new version, this problem is fixed for you?

**Comment by poke1024** [comment]
I guess this is fixed now. Closing this.
