### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by pat-s** [KDE-mac/homebrew-kde#158]
Hi guys,

while trying to install various formulas of this tap, I encountered several issues.

@sl1pkn07 helped me a lot and has some fixed formuluas in his branch.
However, some do not work ootb (e.g. `kate`) as they depend on formulas of the `master` branch which do no exist in `master` but only in the branch of @sl1pkn07.

I am curious why you are doing this parallel development here and the fixes of @sl1pkn07 are not (regulary) merged into master? The branch is currently 65 commits ahead of `master`.

Currently my status is as follows: 
* I have `kate` running but without plugins
* I have `dolphin` running but without visible folders

Whats your opinion on having a Gitter/Slack group for discussing such issues/questions?

Eager to help and thanks for your effort 👍

**Comment by sl1pkn07** [comment]
the next release of frameworks (5.40) is supposed out tomorrow

when out, i want make the changes, test, and do a PR for merge in master

**Comment by pat-s** [comment]
Alright, cool. 

Whats your opinion about a Gitter group and an updated README with some notes for specific formulas? Its easier than browsing the issues for all errors that occured during `make` of some formula as long as they have not been fixed.

**Comment by sl1pkn07** [comment]
frameworks 5.40 is out. but i'm still need test kdevplatform&co

@yurikoles can you wait?

**Comment by yurikoles** [comment]
@sl1pkn07 of course, I will wait. Do you want to update frameworks by yourself?

**Comment by sl1pkn07** [comment]
@yurikoles yes. i see it and duplicate it for applications (and patch fix for previnting broke url/shasums patch type) 

i see you update the frameworks.... this is bad for merge my branch in master :(

**Comment by sl1pkn07** [comment]
finaly. i think i done all ok

please test!

**Comment by pat-s** [comment]
Currently installing all formulas.

* Which formula is responsible for folders appearing in `dolphin`?
* Which formula is responsible for plugins in `kate`?

**Comment by sl1pkn07** [comment]
how you launch the programs?, if is by console, you need set before 

QT_PLUGIN_PATH=$(brew --prefix)/lib/qt5/plugins

in your enviroment

(this can do some wrong function in other Qt-based programs)

what kate plugins you mean?
![captura de pantalla 2017-11-12 a las 15 08 28](https://user-images.githubusercontent.com/462213/32699784-6896909a-c7bb-11e7-9634-26ac8c98f838.png)

for dolphin , is kio (i whant to add kio-extra package for more funcionality)
![captura de pantalla 2017-11-12 a las 15 11 02](https://user-images.githubusercontent.com/462213/32699803-ba89f6a8-c7bb-11e7-937f-1206b71d6a55.png)

**Comment by pat-s** [comment]
I launch them from `~/Applications/KDE` by double-clicking `kate.app`.

The plugin setting in `kate` is empty for me and I see no folders in `dolphin` :/.  
Setting `QT_PLUGIN_PATH` did not help. I am on `high_sierra` btw.

**Comment by sl1pkn07** [comment]
you done all the caveats? (frameworks) include
