### ISSUE TITLE
kf5-tier*-frameworks download fails

### ISSUE THREAD

**Issue by pat-s** [KDE-mac/homebrew-kde#162]
```
Installing kf5-tier3-frameworks from kde-mac/kde
==> Downloading https://sl1pkn07.wtf/paste/view/raw/f4513d60

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sl1pkn07.wtf:443
Error: Failed to download resource "kf5-tier3-frameworks"
Download failed: https://sl1pkn07.wtf/paste/view/raw/f4513d60
```

The same for `tier1` and `tier2`.

**Comment by sl1pkn07** [comment]
Oh, yes i forget keep my server online, sorry

**Comment by yurikoles** [comment]
@sl1pkn07 here is the repo for patches https://github.com/KDE-mac/formula-patches

**Comment by sl1pkn07** [comment]
Is not a patch, is only a "txt" with this content

```:)```

Is possible use URI file:\\\ instead off http/ftp?

**Comment by yurikoles** [comment]
@sl1pkn07 look here https://github.com/KDE-mac/homebrew-kde/blob/master/kf5-kcoreaddons.rb

**Comment by sl1pkn07** [comment]
Https no, file, for local uri

**Comment by yurikoles** [comment]
Yes, you can embed it

**Comment by sl1pkn07** [comment]
roger o7

**Comment by sl1pkn07** [comment]
~~~
Error: no implicit conversion of Symbol into String
Please report this bug:
~~~

**Comment by yurikoles** [comment]
@sl1pkn07 how you get this error?

P.S. sent you invite in google hangouts.

**Comment by sl1pkn07** [comment]
simply with

url :DATA

__END__
>something< 
or 
>empty< 
or 
>
diff --git a/empty b/empty
new file mode 100644
index 0000000..e69de29
<

**Comment by yurikoles** [comment]
>url :DATA

should be `patch :DATA`

**Comment by sl1pkn07** [comment]
er. no, i think you in mistake. 

the `url` points to my server/main rig (my domain is my pc, that serve a pastebin service), and this is now down (due a GPU RIP)

i what to point `url` to "/dev/null" or some file in local

because seems `class FooBar < Formula`  need set `url` as mandatory

if not, i make this while try it

```
  url "file://localhost/usr/local/Homebrew/Library/Homebrew/test/support/fixtures/cask/naked_non_executable"
  sha256 "54d626e08c1c802b305dad30b7e54a82f102390cc92c7d4db112048935236e9c"
```

and seems works. but i'm not sure if is ok

**Comment by yurikoles** [comment]
@sl1pkn07 give me your patch please. I will try to elaborate it.

**Comment by sl1pkn07** [comment]
no exist patch for i want do

na. i'll make a empty file in the repo (tools/empty) and change
```
url "https://sl1pkn07.wtf/paste/view/raw/f4513d60"
```
to
```
url "https://github.com/KDE-mac/homebrew-kde/blob/master/tools/empty"
```
in all meta formulas

is ok for you?

**Comment by yurikoles** [comment]
why are you doing that?

**Comment by sl1pkn07** [comment]
because i want make a metapackage, no need download sources of any type, but url (wich is used for download the sources) a can be empty or not set

"https://sl1pkn07.wtf/paste/view/raw/f4513d60" is a paste with this content: `:)` but now is down.

**Comment by sl1pkn07** [comment]
69c4779a5088f94f812db574d8db6bf3b112bf23

fixed
