### ISSUE TITLE
phonon now fails to build

### ISSUE THREAD

**Issue by rlancaste** [KDE-mac/homebrew-kde#164]
I had phonon building on OS X for KStars using the VLC backend about 2 weeks ago with no problem using this repository and my build script.  But then yesterday I decided to rebuild  all of the KDE dependencies in case there were any updates.  Now Phonon fails to build.  It gets about 98% of the way done, but fails with a linker error.  This did not happen 2 weeks ago.

ld: file not found: @rpath/QtDBus.framework/Versions/5/QtDBus for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [designer/phononwidgets.so] Error 1
make[1]: *** [designer/CMakeFiles/phononwidgets.dir/all] Error 2

Any help would be greatly appreciated.

Thanks!

**Comment by rlancaste** [comment]
The strange part is, I looked where it says the file QtDBus should be, and the file is there, it is a link to the file, but it is there nonetheless, and the link is not broken.

**Comment by sl1pkn07** [comment]
need more log

you try uninstall the package (adding --ignore-dependencies) and build again from zero?

**Comment by rlancaste** [comment]
I did manage to get it to work using a different version of qt.  I'm still not sure what was wrong, but the dependencies all build again and I can build KStars once more.  Thanks for your help

**Comment by sl1pkn07** [comment]
Tnx
