### ISSUE TITLE
DBus: no available service

### ISSUE THREAD

**Issue by KINFOO** [KDE-mac/homebrew-kde#17]
Hi,

I am using **Xcode 4.3.6** and installed DBus without issues:

``` sh
$ brew install d-bus
```

I followed the description in the D-Bus formula to set up the LaunchAgent.

``` sh
$ ln -sfv /usr/local/opt/d-bus/*.plist ~/Library/LaunchAgents
$ launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
```

Then I meanly reboot and enter troubleshooting commands:

``` sh
$ echo $DBUS_LAUNCHD_SESSION_BUS_SOCKET
/tmp/launch-AScZJn/unix_domain_listener
$ `brew --prefix`/opt/qt5/bin/qdbus
zsh: no such file or directory: /usr/local/opt/qt5/bin/qdbus
```

_No service_, did I miss something?

Kevin

![xcodeversion](https://cloud.githubusercontent.com/assets/154818/5577646/28f40d76-9016-11e4-97e4-1971cdeaf975.png)

**Comment by haraldF** [comment]
Seems you first installed Qt 5 and then d-bus? Did you try removing Qt5 and reinstalling with --with-dbus?

**Comment by KINFOO** [comment]
Yes I did.

I cam try again uninstalling qt5 with special options if it helps.

Kevin
Le 18 janv. 2015 11:51, "Harald Fernengel" <notifications@github.com> a
écrit :
