### ISSUE TITLE
Add a do-all-caveats.sh script to tools?

### ISSUE THREAD

**Issue by arichardson** [KDE-mac/homebrew-kde#171]
Would it make sense to add a script to the tools directory that does all the caveats needed to run GUI applications like kate? This would make it a lot easier to get a working environment.

Or is there some way to run some shell command outside of the brew sandbox as a post-install step?

**Comment by sl1pkn07** [comment]
`brew info kf5*` for the frameworks

**Comment by arichardson** [comment]
Yes but then I still need to scan through all that output and manually copy the commands into my terminal.

I was mostly wondering whether you would be interested to add such a script to the repository. I can write that script and submit it as a pull request if you want.

**Comment by sl1pkn07** [comment]
can add this into each application instead of a general tool

BTW, the support of the application is still in experimental stage (in mac, with brew). needs much work for done

**Comment by yurikoles** [comment]
@arichardson could you send a PR please?
