### ISSUE TITLE
Error installing kf5-extra-cmake-modules

### ISSUE THREAD

**Issue by waseem-cs** [KDE-mac/homebrew-kde#183]
I tried installing kdevelop on macOS which has kf5-extra-cmake-modules as dependency. But got the following error message when it started installing it

==> Installing kf5-extra-cmake-modules from kde-mac/kde
==> Downloading https://download.kde.org/stable/frameworks/5.40/extra-cmake-modules-5.40.0.tar.xz
Already downloaded: /Users/waseem/Library/Caches/Homebrew/kf5-extra-cmake-modules-5.40.0.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-extra-cmake-modules/5.40.0_1 -DCMAKE_BUILD_TYPE=Release
==> make install
Last 15 lines from /Users/waseem/Library/Logs/Homebrew/kf5-extra-cmake-modules/02.make:
    from docutils.utils.code_analyzer import Lexer, LexerError
  File "/Library/Python/2.7/site-packages/docutils/utils/code_analyzer.py", line 13, in <module>
    from pygments.lexers import get_lexer_by_name
  File "/Library/Python/2.7/site-packages/pygments/lexers/__init__.py", line 20, in <module>
    from pygments.plugin import find_plugin_lexers
  File "/Library/Python/2.7/site-packages/pygments/plugin.py", line 39, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
make[2]: *** [docs/doc_format_man] Error 1
make[1]: *** [docs/CMakeFiles/documentation.dir/all] Error 2
make: *** [all] Error 2

Not sure what the problem is

**Comment by sl1pkn07** [comment]
Need more log please

Greetings

**Comment by waseem-cs** [comment]
That was the complete error message on the console.

Regards,
Waseem

**Comment by yurikoles** [comment]
@waseem-cs 
```brew gist-logs kf5-extra-cmake-modules```

**Comment by waseem-cs** [comment]
It gave me this message

https://gist.github.com/4941a7a7d093c0421d59faebe4bd2edc <https://gist.github.com/4941a7a7d093c0421d59faebe4bd2edc>


Regards,
Waseem

**Comment by sl1pkn07** [comment]
Try uninstall sphynx-doc first. Seems brew build Sphynx with python3 but not with python2

In the next version of frameworks, i'll try build all with python3

**Comment by waseem-cs** [comment]
brew uninstall sphynx-doc
Error: No such keg: /usr/local/Cellar/sphynx-doc
MacBook-Pro:include waseem$ brew remove sphynx-doc
Error: No such keg: /usr/local/Cellar/sphynx-doc

Is there another way to uninstall it?

Regards,
Waseem

**Comment by sl1pkn07** [comment]
Maybe i misspell the name of the formula.

Yep. Is sphinx-doc

**Comment by waseem-cs** [comment]
MacBook-Pro:include waseem$ brew remove sphinx-doc
Error: No such keg: /usr/local/Cellar/sphinx-doc

Nope! No again!

Regards,
Waseem

**Comment by waseem-cs** [comment]
This may help 

ls  /usr/local/Cellar/ 
boost		fdk-aac		gdbm		isl		libmpc		libvorbis	mpfr@2		python3		wget
cloog		freetype	gettext		isl011		libmpc08	libvpx		openssl		qt		x264
cloog018	gcc		gmp		isl@0.11	libmpc@0.8	makedepend	opus		readline	xvid
cmake		gcc49		gmp4		lame		libogg		mpfr		pcre		sqlite		xz
faac		gcc@4.9		gmp@4		libav		libpng		mpfr2		pkg-config	texi2html	yasm

Regards,
Waseem

**Comment by sl1pkn07** [comment]
what is you output of:
`pip show sphinx` 

?

**Comment by waseem-cs** [comment]
I did a 'pip3 install sphinx’ and then 'brew install kf5-extra-cmake-modules’. Got it done finally!!

I am actually trying to install kdevelop, which required the kf5-extra-cmake-modules. Have restarted the process now…its currently installing…hopefully things will work as expected now.

Thanks a lot for the help, the fixing of the bug, your time on the software development and the software itself!! 

Regards,
Waseem

**Comment by waseem-cs** [comment]
Thanks!

**Comment by sl1pkn07** [comment]
for the record. extra-cmake-modules not need sphinx for build (can use it, but not is necessary). this error is trigger by install the some users have installed sphinx by PIP with python3

uninstall sphinx from PIP or install it with PIP in python2 environment solve the issue

in a future release,  i want to build all kf5 frameworks/apps (if call python for build) with python3
