### ISSUE TITLE
cannot install KDevelop

### ISSUE THREAD

**Issue by FranklinYu** [KDE-mac/homebrew-kde#186]
It complains that it cannot find the `languages/clang/CMakeLists.txt` file to patch. I myself cannot find it in [repository](https://cgit.kde.org/kdevelop.git/tree/?h=v5.2.0) either.

**Comment by sl1pkn07** [comment]
i'm not sure why, but this is done when send PR to @yurikoles repo, but is not merged, or only merge partial to master

https://github.com/yurikoles/homebrew-kde/pull/1/commits/ca199b5ca1708a2c186a6987dcafc033eddcbd8b#diff-c38e0ec5617dfec4945a05b3a76a85c8.diff

**Comment by franklinyu** [comment]
I think there is still one `language` left unchanged.

**Comment by sl1pkn07** [comment]
tested myself. yep, is a typo. but patch ok

**Comment by franklinyu** [comment]
It compiles, but does not run. Any way to debug?

**Comment by prakgoya** [comment]
It runs now. Please check.
