### ISSUE TITLE
Okular can't handle the file open event in macOS

### ISSUE THREAD

**Issue by vaboro** [KDE-mac/homebrew-kde#188]
Files can only be opened via the "Files" menu or via command line:

open -a "okular.app" --args "filename"

Am I missing something?

**Comment by vaboro** [comment]
Can be bypassed with Automator.

**Comment by yurikoles** [comment]
Hi @vaboro,
Please share your automato file, if it's possible.

**Comment by vaboro** [comment]
Sure, here it is. It is a very simple application stub.
[OkularAuto.zip](https://github.com/KDE-mac/homebrew-kde/files/1864326/OkularAuto.zip)
Without this application stub when I open context menu on a file and choose "Open with..." and then Okular.app, nothing is actually opened.
I added an action of getting selected files from Finder, and then the Automator passes the selected object(s) to Okular.app via command line.
