### ISSUE TITLE
Problem running Kate

### ISSUE THREAD

**Issue by nbigaouette** [KDE-mac/homebrew-kde#19]
I've forked the repo to update the framework to 5.6.0.

I've fixed some small issues, for example added dependency of kate on oxygen-icons. Most importantly, I patched kio's CMakeLists.txt to remove its check on X11. Qt5 on OSX should not use X11, but I do have it installed for other purpose and the cmake file is picking it up. See https://github.com/Homebrew/homebrew/issues/36660 
A better patch should probably be submitted upstream at some point.

Unfortunately, I cannot run kate. It seems it cannot find it's UI files:

```
/Applications/KDE/kate.app/Contents/MacOS/kate
kf5.kcoreaddons.kdirwatch: fsWatcher->addPath "/Users/nicolas/Library/Application Support/kate/sessions"
kate: Warning, session file not found:  "/Users/nicolas/Library/Application Support/kate/anonymous.katesession"
kate: Warning, session file not found:  "/Users/nicolas/Library/Application Support/kate/anonymous.katesession"
Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kglobalaccel was not provided by any .service files")
cannot find .rc file "kateui.rc" for component "kate"
cannot find .rc file "kateui.rc" for component "kate"
cannot find .rc file "katepart5ui.rc" for component "katepart"
kf5.kiconthemes: "Theme tree: (Oxygen)"
Segmentation fault: 11
```

This seems related to issue #7. From what I understand, every formulas are installed in their own prefix but KF5 expect them to all be in the same one. Same thing for dbus. Is that right? In that case, could the required files be symlinked in brew --prefix (new to homebrew, don't know if it's possible)?

Thanks!

**Comment by haraldF** [comment]
I have some symlinks in kf5-extra-cmake-modules.rb:
    ln_sf Dir["#{HOMEBREW_PREFIX}/share/kxmlgui5"]

in order to map the files to share/kxmlgui5, but it seems I forgot to set a few. If you'd like to debug, add some qDebug() statements where the *.rc files are opened and figure out which directories kf5 is looking at. We either have to fix kf5, or add some more symbolic links

**Comment by nbigaouette** [comment]
Hum...

One of the directories where Kate searches for its ui in `~/Library/Application Support/kxmlgui5/kate/kateui.rc`. This comes from kxmlguiclient.cpp's line 227:
`QStandardPaths::GenericDataLocation, QStringLiteral("kxmlgui5/") + filter`
(see http://api.kde.org/frameworks-api/frameworks5-apidocs/kxmlgui/html/kxmlguiclient_8cpp_source.html)

For whatever reason, the link create in kf5-extra-cmake-modules.rb (from `ln_sf Dir["#{HOMEBREW_PREFIX}/share/kxmlgui5"], "#{ENV['HOME']}/Library/Application Support/"`) was not present on my system. Re-installing this formula let kate open.

Kate is now opened:
![kate](https://cloud.githubusercontent.com/assets/112988/6120685/faa69248-b0a6-11e4-952c-222eaa201efd.png)

Issues:
* No icons in toolbar.
* No way to configure the editor. Missing something? A component or framework?

**Comment by haraldF** [comment]
FYI - the X11 problem in KIO is already fixed upstream by Christoph (see 46ca25e6d5766fd2fb9dbbe1f91853356961ae1c)

**Comment by stephanemagnenat** [comment]
I have similar issues.

**Comment by nbigaouette** [comment]
People on kde-mac mailing list pointed me to this code review:
https://codereview.qt-project.org/#/c/103277/

There's also some discussion on the mailing list about Kate crashing on macport:
http://mail.kde.org/pipermail/kde-mac/2014-December/002625.html

The most important issue is probably QStandardPath which is not a flexible as the KStandardPath was. Without this, it's going to be quite hard to use KDE applications on OSX, be it through macports or homebrew or anything else.

The problem is that applications cannot find each other, including the kf5 frameworks...

**Comment by Plaristote** [comment]
I concur to all of that. Also, there's no syntax coloring available. I do not know from where are those supposed to come from, but I'd definitely like to have them.

**Comment by mccann** [comment]
Hi,

I've fixed the icons loading issue with Kate on my fork of this project.  As soon as it's stable I'll request a pull. 

https://github.com/mccann/homebrew-kf5

I also notice that preferences is now available in Kate.app . I don't think that was my doing, perhaps just got fixed in the newer sources, which I did include.

Testing/Review would be appreciated.

**Comment by krf** [comment]
@mccann: Can you prepare a PR?
