### ISSUE TITLE
Error: Failure while executing: patch -g 0 -f -p1 -i /private/tmp/okular--patch-20171216-19307-kgbvmn/D8612.diff

### ISSUE THREAD

**Issue by vaboro** [KDE-mac/homebrew-kde#191]
$ brew install okular
==> Installing okular from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/17.12.0/src/okular-17.12.0.tar.xz
==> Downloading https://raw.githubusercontent.com/RJVB/macstrop/master/kf5/kf5-okular/files/patch-plugin-depends.diff
==> Downloading https://phabricator.kde.org/file/data/grwvte52ekjslqdazu4i/PHID-FILE-7mbnuozecsvft7hndonr/D8612.diff
==> Patching
==> Applying patch-plugin-depends.diff
patching file mobile/components/CMakeLists.txt
Hunk #1 succeeded at 30 (offset 1 line).
patching file CMakeLists.txt
Hunk #1 succeeded at 215 with fuzz 1 (offset 25 lines).
patching file core/utils.cpp
==> Applying D8612.diff
patching file generators/spectre/CMakeLists.txt
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file generators/spectre/CMakeLists.txt.rej
Error: Failure while executing: patch -g 0 -f -p1 -i /private/tmp/okular--patch-20171216-19307-kgbvmn/D8612.diff

**Comment by ynakao** [comment]
This patch was necessary to build previous okular version(#184), but it is no longer needed now. I made the PR(#192), please wait to merge.

**Comment by vaboro** [comment]
Now it goes some way further but generates another error:

$ brew install okular
==> Installing okular from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/17.12.0/src/okular-17.12.0.tar.xz
==> Downloading https://raw.githubusercontent.com/RJVB/macstrop/master/kf5/kf5-okular/files/patch-plugin-depends.diff
==> Patching
==> Applying patch-plugin-depends.diff
patching file mobile/components/CMakeLists.txt
Hunk #1 succeeded at 30 (offset 1 line).
patching file CMakeLists.txt
Hunk #1 succeeded at 215 with fuzz 1 (offset 25 lines).
patching file core/utils.cpp
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/okular/17.12.0_1 -DCMA
==> make install
Last 15 lines from ~/Library/Logs/Homebrew/okular/02.make:
#include <zipconf.h>
         ^
1 error generated.
make[2]: *** [generators/chm/CMakeFiles/okularGenerator_chmlib.dir/lib/ebook_epub.cpp.o] Error 1
make[1]: *** [generators/chm/CMakeFiles/okularGenerator_chmlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object generators/djvu/CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o
cd /tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DHAVE_SPEECH -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"okular_djvu\" -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -DokularGenerator_djvu_EXPORTS -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/generators/djvu -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/include -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0 -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/core/synctex -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/core -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/generators/djvu/../.. -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build -I/usr/local/include/phonon4qt5 -I/usr/local/include/phonon4qt5/KDE -I/usr/local/opt/zlib/include -I/usr/local/include -isystem /usr/local/include/KF5/KCoreAddons -isystem /usr/local/include/KF5 -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/include/KF5/KXmlGui -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/include/KF5/KConfigCore -isystem /usr/local/include/KF5/KConfigWidgets -isystem /usr/local/include/KF5/KCodecs -isystem /usr/local/include/KF5/KWidgetsAddons -isystem /usr/local/include/KF5/KConfigGui -isystem /usr/local/include/KF5/KAuth -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/include/KF5/KI18n  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o -c /tmp/okular-20171219-7521-dybxih/okular-17.12.0/generators/djvu/kdjvu.cpp
[ 73%] Building CXX object generators/djvu/CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o
cd /tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DHAVE_SPEECH -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"okular_djvu\" -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -DokularGenerator_djvu_EXPORTS -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/generators/djvu -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/include -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0 -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/core/synctex -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/core -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/generators/djvu/../.. -I/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build -I/usr/local/include/phonon4qt5 -I/usr/local/include/phonon4qt5/KDE -I/usr/local/opt/zlib/include -I/usr/local/include -isystem /usr/local/include/KF5/KCoreAddons -isystem /usr/local/include/KF5 -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/include/KF5/KXmlGui -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/include/KF5/KConfigCore -isystem /usr/local/include/KF5/KConfigWidgets -isystem /usr/local/include/KF5/KCodecs -isystem /usr/local/include/KF5/KWidgetsAddons -isystem /usr/local/include/KF5/KConfigGui -isystem /usr/local/include/KF5/KAuth -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/include/KF5/KI18n  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o -c /tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/mocs_compilation.cpp
[ 73%] Linking CXX shared module okularGenerator_djvu.so
cd /tmp/okular-20171219-7521-dybxih/okular-17.12.0/build/generators/djvu && /usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/okularGenerator_djvu.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -bundle -Wl,-headerpad_max_install_names -multiply_defined suppress  -o okularGenerator_djvu.so CMakeFiles/okularGenerator_djvu.dir/generator_djvu.cpp.o CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o -Wl,-rpath,/tmp/okular-20171219-7521-dybxih/okular-17.12.0/build ../../libOkular5Core.8.0.0.dylib /usr/local/lib/libdjvulibre.dylib /usr/local/lib/libKF5XmlGui.5.40.0.dylib /usr/local/opt/qt/lib/QtPrintSupport.framework/QtPrintSupport /usr/local/lib/libKF5ConfigWidgets.5.40.0.dylib /usr/local/lib/libKF5I18n.5.40.0.dylib /usr/local/lib/libKF5ConfigGui.5.40.0.dylib /usr/local/opt/qt/lib/QtXml.framework/QtXml /usr/local/lib/libKF5ConfigCore.5.40.0.dylib /usr/local/lib/libKF5Codecs.5.40.0.dylib /usr/local/lib/libKF5Auth.5.40.0.dylib /usr/local/lib/libKF5CoreAddons.5.40.0.dylib /usr/local/lib/libKF5WidgetsAddons.5.40.0.dylib /usr/local/opt/qt/lib/QtWidgets.framework/QtWidgets /usr/local/opt/qt/lib/QtGui.framework/QtGui /usr/local/opt/qt/lib/QtDBus.framework/QtDBus /usr/local/opt/qt/lib/QtCore.framework/QtCore
[ 73%] Built target okularGenerator_djvu
make: *** [all] Error 2

**Comment by vaboro** [comment]
After kf5 update still can not build:
```
$ brew install okular
==> Installing okular from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/17.12.0/src/okular-17.12.0.tar.xz
==> Downloading https://raw.githubusercontent.com/RJVB/macstrop/master/kf5/kf5-okular/files/patch-plugin-depends.diff
==> Patching
==> Applying patch-plugin-depends.diff
patching file mobile/components/CMakeLists.txt
Hunk #1 succeeded at 30 (offset 1 line).
patching file CMakeLists.txt
Hunk #1 succeeded at 215 with fuzz 1 (offset 25 lines).
patching file core/utils.cpp
patch unexpectedly ends in middle of line
Hunk #2 succeeded at 144 with fuzz 1.
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/okular/17.12.0_1 -
==> make install
Last 15 lines from ~/Library/Logs/Homebrew/okular/02.make:
#include <zipconf.h>
         ^
1 error generated.
make[2]: *** [generators/chm/CMakeFiles/okularGenerator_chmlib.dir/lib/ebook_epub.cpp.o] Error 1
make[1]: *** [generators/chm/CMakeFiles/okularGenerator_chmlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object generators/djvu/CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o
cd /tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DHAVE_SPEECH -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"okular_djvu\" -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -DokularGenerator_djvu_EXPORTS -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/generators/djvu -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/include -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0 -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/core/synctex -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/core -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/generators/djvu/../.. -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build -I/usr/local/include/phonon4qt5 -I/usr/local/include/phonon4qt5/KDE -I/usr/local/opt/zlib/include -I/usr/local/include -isystem /usr/local/include/KF5/KCoreAddons -isystem /usr/local/include/KF5 -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/include/KF5/KXmlGui -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/include/KF5/KConfigCore -isystem /usr/local/include/KF5/KConfigWidgets -isystem /usr/local/include/KF5/KCodecs -isystem /usr/local/include/KF5/KWidgetsAddons -isystem /usr/local/include/KF5/KConfigGui -isystem /usr/local/include/KF5/KAuth -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/include/KF5/KI18n  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o -c /tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/generators/djvu/kdjvu.cpp
[ 73%] Building CXX object generators/djvu/CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o
cd /tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DHAVE_SPEECH -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"okular_djvu\" -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -DokularGenerator_djvu_EXPORTS -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/generators/djvu -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/include -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0 -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/core/synctex -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/core -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/generators/djvu/../.. -I/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build -I/usr/local/include/phonon4qt5 -I/usr/local/include/phonon4qt5/KDE -I/usr/local/opt/zlib/include -I/usr/local/include -isystem /usr/local/include/KF5/KCoreAddons -isystem /usr/local/include/KF5 -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/include/KF5/KXmlGui -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/include/KF5/KConfigCore -isystem /usr/local/include/KF5/KConfigWidgets -isystem /usr/local/include/KF5/KCodecs -isystem /usr/local/include/KF5/KWidgetsAddons -isystem /usr/local/include/KF5/KConfigGui -isystem /usr/local/include/KF5/KAuth -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/include/KF5/KI18n  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o -c /tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu/okularGenerator_djvu_autogen/mocs_compilation.cpp
[ 73%] Linking CXX shared module okularGenerator_djvu.so
cd /tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build/generators/djvu && /usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/okularGenerator_djvu.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -DNDEBUG -bundle -Wl,-headerpad_max_install_names -multiply_defined suppress  -o okularGenerator_djvu.so CMakeFiles/okularGenerator_djvu.dir/generator_djvu.cpp.o CMakeFiles/okularGenerator_djvu.dir/kdjvu.cpp.o CMakeFiles/okularGenerator_djvu.dir/okularGenerator_djvu_autogen/mocs_compilation.cpp.o -Wl,-rpath,/tmp/okular-20180110-47220-19jcqwj/okular-17.12.0/build ../../libOkular5Core.8.0.0.dylib /usr/local/lib/libdjvulibre.dylib /usr/local/lib/libKF5XmlGui.5.41.0.dylib /usr/local/opt/qt/lib/QtPrintSupport.framework/QtPrintSupport /usr/local/lib/libKF5ConfigWidgets.5.41.0.dylib /usr/local/lib/libKF5I18n.5.41.0.dylib /usr/local/lib/libKF5ConfigGui.5.41.0.dylib /usr/local/opt/qt/lib/QtXml.framework/QtXml /usr/local/lib/libKF5ConfigCore.5.41.0.dylib /usr/local/lib/libKF5Codecs.5.41.0.dylib /usr/local/lib/libKF5Auth.5.41.0.dylib /usr/local/lib/libKF5CoreAddons.5.41.0.dylib /usr/local/lib/libKF5WidgetsAddons.5.41.0.dylib /usr/local/opt/qt/lib/QtWidgets.framework/QtWidgets /usr/local/opt/qt/lib/QtGui.framework/QtGui /usr/local/opt/qt/lib/QtDBus.framework/QtDBus /usr/local/opt/qt/lib/QtCore.framework/QtCore
[ 73%] Built target okularGenerator_djvu
make: *** [all] Error 2
```

**Comment by vaboro** [comment]
```
$ ls /usr/local/include/zipconf.h
ls: /usr/local/include/zipconf.h: No such file or directory
$ find /usr -name "zipconf.h"
/usr/local/Cellar/libzip/1.3.0/lib/libzip/include/zipconf.h
$ cd /usr/local/include && ln -s ../Cellar/libzip/1.3.0/lib/libzip/include/zipconf.h zipconf.h
```
Solved. Closing the issue.
