### ISSUE TITLE
Installing kmymoney (kdoctools v.s. perl URI)

### ISSUE THREAD

**Issue by myzinsky** [KDE-mac/homebrew-kde#193]
==> Installing haraldf/kf5/kmymoney dependency: KDE-mac/kde/kf5-kdoctools
==> Downloading https://download.kde.org/stable/frameworks/5.40/kdoctools-5.40.0.tar.xz
Already downloaded: /Users/myzinsky/Library/Caches/Homebrew/kf5-kdoctools-5.40.0.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoc
Last 15 lines from /Users/myzinsky/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.26.1")
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND)
CMake Error at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)

I dont understand this, because I have URI installed ...

**Comment by myzinsky** [comment]
The problem was that I had to many different perl version installed. I removed home-brew completely and started from scratch and followed the caveats of the perl package and the kdoctools:

```bash
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bash_profile
brew install cpanminus
cpanm install URI 
```

**Comment by vaboro** [comment]
I encounted the same error when upgrading kf5-kdoctools.
I found out that it might be due to confusion about where perl modules had been installed.

> $ brew info kf5-kdoctools
> ...
> ==> Caveats
> Before install of this formula you need to run:
>   brew install cpanminus
>   cpanm URI
> ...

However,

> $ brew info perl
> ...
> ==> Caveats
> By default non-brewed cpan modules are installed to the Cellar. If you wish
> for your modules to persist across updates we recommend using `local::lib`.
> 
> You can set that up like this:
>   PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
>   echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bash_profile

After executing both sets of Caveats I had two folders with perl modules: $HOME/.cpan and $HOME/perl5, and a $HOME/.cpanm folder. I presumed that cpan modules were in fact not installed to the Cellar but to $HOME/.cpan
I removed cpanminus and the three directories. Then I installed module URI with cpan into $HOME/.cpan: $ cpan URI.
After that I was able to upgrade kf5-kdoctools.

**Comment by bmihaila** [comment]
Just adding that
`$❯ cpan install URI::Escape`
fixed the issue for me. The above installs it to `/usr/local/Cellar/perl/...` instead of the home directory but that also means no need for those `.bash_profile` hacks.

**Comment by vaboro** [comment]
Indeed, I wondered where all those .pm files in the $HOME/.cpan directory even though the issue was solved for me. Now that is clarified along with the incorrect assumption.

**Comment by diversys** [comment]
@vaboro Thanks a lot! that fixed it for me as well!

**Comment by vaboro** [comment]
I presume installing cpanminus is overkill; whereas, perl caveats may indeed be useful.
