### ISSUE TITLE
kf5-kdnssd: error: no matching function for call to 'DNSServiceResolve'

### ISSUE THREAD

**Issue by jdknox** [KDE-mac/homebrew-kde#200]
While trying to install `kdnssd-5.42.0` I came across this error:
```
Last 15 lines from /Users/<USER>/Library/Logs/Homebrew/kf5-kdnssd/02.make:
DNSServiceErrorType DNSSD_API DNSServiceRegister
                              ^
/tmp/kf5-kdnssd-20180116-19924-1uhn31z/kdnssd-5.42.0/src/mdnsd-remoteservice.cpp:85:9: error: no matching function for call to 'DNSServiceResolve'
    if (DNSServiceResolve(&ref, 0, 0, d->m_serviceName.toUtf8(), d->m_type.toLatin1().constData(),
        ^~~~~~~~~~~~~~~~~
/usr/include/dns_sd.h:1616:31: note: candidate function not viable: no known conversion from 'QByteArray' to 'const char *' for 4th argument
DNSServiceErrorType DNSSD_API DNSServiceResolve
```

There were also similar errors in `src/mdnsd-publicservice.cpp` and `src/mdnsd-servicebrowser.cpp`.  I was able to get the package to compile and install by converting the `QByteArray`s to `const char *`.

I'll include a patch in case this is an acceptable fix.

[kf5-kdnssd_DNSServiceResolve.diff.txt](https://github.com/KDE-mac/homebrew-kde/files/1637450/kf5-kdnssd_DNSServiceResolve.diff.txt)

**Comment by ndesmoul** [comment]
I have exactly the same error. I didn't try the proposed patch though.

**Comment by HesselM** [comment]
Same issue here. Do you have a MR or something for this?
