### ISSUE TITLE
Patch error for kf5 wallet and kf5 sonnet

### ISSUE THREAD

**Issue by rlancaste** [KDE-mac/homebrew-kde#205]
This did not happen until recently.

==> Installing kde-mac/kde/kf5-kwallet
==> Downloading https://download.kde.org/stable/frameworks/5.42/kwallet-5.42.0.tar.xz
Already downloaded: ~/Library/Caches/Homebrew/kf5-kwallet-5.42.0.tar.xz
==> Patching
patching file CMakeLists.txt
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
patching file src/runtime/kwallet-query/src/CMakeLists.txt
patching file src/runtime/kwalletd/CMakeLists.txt
Hunk #1 succeeded at 119 (offset 4 lines).
Error: Failure while executing: patch -g 0 -f -p1

==> Installing kde-mac/kde/kf5-kxmlgui dependency: KDE-mac/kde/kf5-sonnet
==> Downloading https://download.kde.org/stable/frameworks/5.42/sonnet-5.42.0.tar.xz
Already downloaded: ~/Library/Caches/Homebrew/kf5-sonnet-5.42.0.tar.xz
==> Patching
patching file src/plugins/nsspellchecker/CMakeLists.txt
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file src/plugins/nsspellchecker/CMakeLists.txt.rej
Error: Failure while executing: patch -g 0 -f -p1

**Comment by wwtalwtaw** [comment]
The CMakeLists.txt of both kf5-kwallet and kf5-sonnet have already been updated, resulting in the conflict with Homebrew's patch.

Now you need to update the patch by hand, which is quite easy. All need to do is to replace two files in `/usr/local/Homebrew/Library/Taps/kde-mac/homebrew-kde` with the files I provide.

Replace kf5-kwallet.rb with [kf5-kwallet.rb](https://gist.github.com/wwtalwtaw/61f887e1597d7f641f0f93238b446fd1).

Replace kf5-sonnet.rb with [kf5-sonnet.rb](https://gist.github.com/wwtalwtaw/18d2bee3bc2c5db32fccda3c9245cdc5).

**Comment by yurikoles** [comment]
@wwtalwtaw pull requests are welcome

**Comment by xywei** [comment]
It seems that `kf5-kimageformats.rb` has the same issue.

**Comment by wwtalwtaw** [comment]
@xywei you could revise the `kf5-kimageformats.rb` based on [the change file](https://github.com/KDE/kimageformats/commit/04e2ee01cb100d78896e0e226a0e2388c94be83c#diff-ec0320374b211a2927a2f962a4125487).

**Comment by yurikoles** [comment]
Fixed in #217
