### ISSUE TITLE
Having trouble installing okular

### ISSUE THREAD

**Issue by hammadshaikhha** [KDE-mac/homebrew-kde#206]
I tried using the instructions to install okular. The following to steps went fine:

brew tap kde-mac/kde
brew install dbus

But I ran into a error when I did, brew install kde-mac/kde/okular

First Error:
curl: (35) Server aborted the SSL handshake
Error: Failed to download resource "cmake"
Download failed: https://homebrew.bintray.com/bottles/cmake-3.10.2.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.

Second Error:
-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20180129-14720-whzi2r/kdoctools-5.42.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20180129-14720-whzi2r/kdoctools-5.42.0/build/CMakeFiles/CMakeError.log".

Error: A newer Command Line Tools release is available. Update them from Software Update in the App Store.

**Comment by vaboro** [comment]
Hello, @hammadshaikhha, have you tried updating Xcode/Command Line Tools?
Sees like curl and/or openssl also needs to be updated.
