### ISSUE TITLE
Okular Can't set default application of pdf file.

### ISSUE THREAD

**Issue by RanTaimu** [KDE-mac/homebrew-kde#209]
OS: macOS High Sierra Version 10.13.3

When I "right click -> Open With -> Other " and choose okular on a pdf file, it just open an empty software. Further, when I choose "Always Open with" option, it gives such an error:
![image](https://user-images.githubusercontent.com/13046439/36659974-4e4a9ea8-1b11-11e8-92ed-d6cae79a27f2.png)

But if I drag a pdf into an already opened okular, it loaded normally.

I just install okular through "brew install okular", and run folllowing cmds:
```
ln -sf "$(brew --prefix)/share/okular" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/kconf_update" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/config.kcfg" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/kservicetypes5" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/kxmlgui5" "$HOME/Library/Application Support"
ln -sf "$(brew --prefix)/share/metainfo" "$HOME/Library/Application Support"
mkdir -p $HOME/Applications/KDE
ln -sf "/usr/local/opt/okular/bin/okular.app" $HOME/Applications/KDE/
```

**Comment by vaboro** [comment]
Hello, @RanTaimu, in order for Okular to open files via context menu you can create an application stup with Automator. See [this](https://github.com/KDE-mac/homebrew-kde/issues/188) issue.

**Comment by RanTaimu** [comment]
@vaboro Thanks for your solution !! But there is still a little problem. It cannot open multiple pdf files when I use the "OkulaAuto.app". Are there any possible ways to solve this problem?

**Comment by vaboro** [comment]
@RanTaimu this one [OkularAuto 2.zip](https://github.com/KDE-mac/homebrew-kde/files/1895529/OkularAuto.2.zip) should do the trick since `man` to `open` says: `--args        All remaining arguments are passed in argv to the application's main() function instead of opened.`
How did you make okular open pdf files? Mine can't. But it opens epubs, jpegs, etc. I tested the new verstion on jpeg files. I probably compiled it w/o pdf support since I was mainly interested in epub.

**Comment by RanTaimu** [comment]
@vaboro Oh... I use okular mainly for pdf reading. The new one still cannot open two or more different pdf files. Actually, there always be only one Okular instance at one time. I'll check it by myself. But at least I can open one pdf file by double-click it. Thanks again for your nice solution!

**Comment by RanTaimu** [comment]
@vaboro OK, I'll try it. Thanks !!

**Comment by yidiq7** [comment]
@vaboro Thanks for the idea. I made a new version [OkularAuto.zip](https://github.com/KDE-mac/homebrew-kde/files/3146138/OkularAuto.zip). It supports multiple instances but it is better to set **Preference -> General -> Open new files in tabs**. You can also open files from shortcuts of folders on the dock with it.
