### ISSUE TITLE
running ./tools/install.sh from homebrew-kde directory

### ISSUE THREAD

**Issue by bracha1969** [KDE-mac/homebrew-kde#210]
The following is only one of the many errors I got while running the tools/install.sh file.

cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PRE
Last 15 lines from /Users/bracha/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.26.1") 
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20180306-5729-1o4b1bm/kdoctools-5.42.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20180306-5729-1o4b1bm/kdoctools-5.42.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/KDE-mac/homebrew-kde/issues

**Comment by yurikoles** [comment]
Hi, @bracha1969 

Why don't you use search? This issue has been discussed so many times!

**Comment by bracha1969** [comment]
I'm new and it asked me to file a report; so, I did.  Maybe not ask people
to report an issue that has been solved or tell them where to go look for
the solution?

Thank You

Mike

**Comment by yurikoles** [comment]
@bracha1969 
This message is automatically generated. Try to search `PerlModules_URI::Escape` in this repo issues.

**Comment by yurikoles** [comment]
We have a [comment](https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/kf5-kdoctools.rb#L39) is formula: 

```
You need to take some manual steps in order to make this formula work: 
ln -sf "$(brew --prefix)/share/kf5" "$HOME/Library/Application Support"
```
