### ISSUE TITLE
SHA256 Mismatch when installing any of the kde-mac/kde/kf5-* packages

### ISSUE THREAD

**Issue by HandsomePixel** [KDE-mac/homebrew-kde#215]
Title says it all.
I am trying to build the latest Krita, and the instructions says to install several KDE Frameworks.
```
* Archive 
 * Completion
 * Config 
 * CoreAddons
 * GuiAddons 
 * I18n 
 * ItemModels 
 * ItemViews
 * KCrash
 * WidgetsAddons 
 * WindowSystem
```
But when trying to install the Config framework (kde-mac/kde/kf5-kcompletion), it says the following:
```
Error: SHA256 mismatch
Expected: 05b02de9dbedc10ddf8e7d8d1d471ae3b81085b3dae817c1468a1b31b007b4e6
Actual: b5b2b3cb0f8e773b7537a09cc4e6bdbe37e0884acb8e60dc8488670a993cd4ed
Archive: /Users/PixelLordFTW/Library/Caches/Homebrew/kf5-kconfig-5.44.0.tar.xz
To retry an incomplete download, remove the file above.
```
This error is pretty much the same for all other frame works, and don't even know how to temporarily edit the SHA256 expected result to "force" install the frameworks.
I can send more info if needed.

**Comment by yurikoles** [comment]
Fixed in d63378d
