### ISSUE TITLE
Cannot install okular (Error: Failure while executing: patch -g 0 -f -p1)

### ISSUE THREAD

**Issue by seakingL** [KDE-mac/homebrew-kde#225]
Hi, I cannot install okular using brew. It seems that something wrong happens in the patching process. Here is the log:

$ brew install okular
==> Installing okular from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/18.04.0/src/okular-18.04.0.tar.xz
Already downloaded: /Users/steven/Library/Caches/Homebrew/okular-18.04.0.tar.xz
==> Downloading https://raw.githubusercontent.com/RJVB/macstrop/master/kf5/kf5-okular/files/patch-pl
Already downloaded: /Users/steven/Library/Caches/Homebrew/okular--patch-33e5e0fa2a10fea2f11a1b975bfee3d87d80215aedb8013ea2d318818a250a46.diff
==> Patching
==> Applying patch-plugin-depends.diff
patching file mobile/components/CMakeLists.txt
Hunk #1 succeeded at 30 (offset 1 line).
patching file CMakeLists.txt
Hunk #1 succeeded at 235 with fuzz 1 (offset 45 lines).
patching file core/utils.cpp
Hunk #1 FAILED at 134.
Hunk #2 FAILED at 144.
2 out of 2 hunks FAILED -- saving rejects to file core/utils.cpp.rej
Error: Failure while executing: patch -g 0 -f -p1

**Comment by sadhen** [comment]
Should be fixed by #237

Notice currently Okular can only be used to view plain text files.
