### ISSUE TITLE
after verifyingdbus works properly how to install Kdevelop

### ISSUE THREAD

**Issue by TappyJune** [KDE-mac/homebrew-kde#234]
i have followed the steps to get KDE but this repo lacks in docs can someone help me install kdevelop

**Comment by yurikoles** [comment]
```
brew install kde-mac/kde/kdevelop
```

**Comment by TappyJune** [comment]
i tried it but got an error :

-- Found Perl: /usr/local/bin/perl (found version "5.26.2") 
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.11.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)


-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20180613-33303-13z7vn9/kdoctools-5.47.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20180613-33303-13z7vn9/kdoctools-5.47.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/KDE-mac/homebrew-kde/issues

These open issues may also help:
Unable to install kf5-kdoctools https://github.com/KDE-mac/homebrew-kde/issues/141

**Comment by yurikoles** [comment]
You need to take some manuall steps which are described in formula source code, see the `caveats` Do:
```
brew edit kf5-kdoctools
```
Or read it online [here](https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/kf5-kdoctools.rb#L33):

**Comment by TappyJune** [comment]
it installed everything but, when installing kdevelop from kde-mac/kde

> [ 52%] Built target KDevPlatformLanguage
make: *** [all] Error 2

**Comment by TappyJune** [comment]
i used `brew install kde-mac/kde/kate` and kate was installed properly with out errors but kdevelop is giving me that error

**Comment by TappyJune** [comment]
i used `brew install kde-mac/kde/kdevelop --head` but i gave me a warning 

> Warning: The post-install step did not complete successfully
You can try again using `brew postinstall kde-mac/kde/kdevelop`

and kdevelop is app itself feels missing stuff like when importing it way different then the windows version and has a problem with project manger since it's not showing anything
<img width="872" alt="screen shot 2018-06-14 at 3 36 14 am" src="https://user-images.githubusercontent.com/40239053/41385404-1f0038a2-6f84-11e8-8338-bbf6486c08a8.png">

**Comment by TappyJune** [comment]
Will For AnyOne who face similar problem, follow these steps top install KDevelop After following the KDE installation steps:

- first, make sure to include the commands in `caveats` [here](https://github.com/KDE-mac/homebrew-kde/blob/326ad3d9bd0eea99263070fc0e8ab6b8c7c9577c/Formula/kdevelop.rb#L59)

- then run the command `brew install kde-mac/kde/kdevelop --HEAD` of-course make sure you can use --Head

- IF you face a problem similar to this saying something about `post-install`

> Warning: The post-install step did not complete successfully
You can try again using `brew postinstall kde-mac/kde/kdevelop`
or when running kdevelop you get a GUI that is weird looking like this
<img width="872" alt="screen shot 2018-06-14 at 3 36 14 am" src="https://user-images.githubusercontent.com/40239053/41385674-cbd26676-6f85-11e8-87a0-68107c9a9b7e.png">

run this command `brew link --overwrite --dry-run kdevelop --HEAD` then `brew unlink kdevelop && brew link kdevelop --HEAD` then run kdevelop again and you should have a similar GUI to the one below. 
<img width="866" alt="screen shot 2018-06-14 at 3 49 10 am" src="https://user-images.githubusercontent.com/40239053/41385696-ecbb28dc-6f85-11e8-81e5-d01649aadeab.png">
