### ISSUE TITLE
Add test block to formula

### ISSUE THREAD

**Issue by FranklinYu** [KDE-mac/homebrew-kde#235]
My KDevelop compiles but does not launch. I have no idea which component is working. The [test block](https://github.com/Homebrew/brew/blob/e3bb004ad799163962acc7b99bd7aaaec9503277/docs/Formula-Cookbook.md#add-a-test-to-the-formula) is very useful tool to debug such case.

**Comment by sl1pkn07** [comment]
in work progress

**Comment by sl1pkn07** [comment]
fixed. now all formulas (except cyrus-sasl) have test block

greetings
