### ISSUE TITLE
okteta source code has moved

### ISSUE THREAD

**Issue by bmihaila** [KDE-mac/homebrew-kde#236]
When installing `okteta` brew runs into the following error:  
```
$❯ brew install okteta
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing okteta from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/18.04.1/src/okteta-18.04.1.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "okteta"
Download failed: https://download.kde.org/stable/applications/18.04.1/src/okteta-18.04.1.tar.xz
```

Seems that the source code download URL indeed does not exist and according to https://community.kde.org/Applications/18.04_Release_Notes `okteta` has moved to its own release cycle so KDE will not ship the code with the Applications release cycle.

After some searching around and this hint from Arch Linux https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/okteta&id=c7b88471176e9a92d1a4c001bf815852b846c95e it seems that the source code is now to be found at https://download.kde.org/stable/okteta/0.25.0/src/ with a new version scheme.

I'll see to update the formula at some point to use above. Not sure though how to make brew use the now much lower version number in package upgrades.

**Comment by yurikoles** [comment]
closed via c452ac6a9b62aee9a220ddbd7d611d248394356d
