### ISSUE TITLE
kf5-kglobalacce download failed 

### ISSUE THREAD

**Issue by ghost** [KDE-mac/homebrew-kde#244]
Hello, I am trying to install KDevelop on mac. The following failed, I presume the mirror location is not available though the file exists in the main kde.org url. Could you please let me know how to edit the mirror? thanks. 

==> Installing kde-mac/kde/kdevelop dependency: KDE-mac/kde/kf5-kglobalacce
==> Downloading https://download.kde.org/stable/frameworks/5.48/kglobalaccel-5.4
==> Downloading from http://mirror.vinahost.vn/kde/stable/frameworks/5.48/kgloba

curl: (18) transfer closed with 83764 bytes remaining to read
Error: Failed to download resource "kf5-kglobalaccel"
Download failed: https://download.kde.org/stable/frameworks/5.48/kglobalaccel-5.48.0.tar.xz

**Comment by sanjitrath** [comment]
tried again to install, it choose a different mirror and continued with download.
