### ISSUE TITLE
kf5-tier1-frameworks download fails

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#248]
kf5-tier*-frameworks download fails #162 , brought up and closed.
seeing:
==> Installing kf5-tier4-frameworks from kde-mac/kde
==> Installing dependencies for kde-mac/kde/kf5-tier4-frameworks: KDE-mac/kde/kf5-tier1-frameworks, KDE-mac/kde/kf5-tier2-frameworks, KDE-mac/kde/kf5-tier3-frameworks
==> Installing kde-mac/kde/kf5-tier4-frameworks dependency: KDE-mac/kde/kf5-tier1-frameworks
==> Downloading file:///tmp/empty
curl: (37) Couldn't open file /tmp/empty
Error: Failed to download resource "kf5-tier1-frameworks"
File does not exist: /tmp/empty

i am very new to homebrew, i assume the file cant be reached, but i have no idea where it should look, so i am here

the process was initiated with this command:
`brew --prefix`/Homebrew/Library/Taps/kde-mac/homebrew-kde/tools/install.sh

**Comment by krrk** [comment]
It looks like a recent commit broke the functionality here. Please run `touch /tmp/empty` then try again.

@yurikoles any idea why in a4e25fecd64cb1ef427046977aa05575e70cfc95 the line `  system "touch", "/tmp/empty"` was removed from these framework files?

**Comment by two-dogs** [comment]
ran `touch /tmp/empty` first,  and tried `brew --prefix/Homebrew/Library/Taps/kde-mac/homebrew-kde/tools/install.sh` again, process completed error free
