### ISSUE TITLE
Dolphin - Invalid protocol Unknown protocol 'file'

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#250]
generally same error as shown here, Dolphin - Invalid protocol #190

executed;

$ /usr/local/Cellar/dolphin/18.04.3/bin/dolphin.app/Contents/MacOS/dolphin ; exit;

and seeing following;

kf5.kio.core: "URL cannot be listed\ntrash:/"
kf5.kio.core: "URL cannot be listed\nfile:///Users/emanuel"
qt.accessibility.core: Cannot create accessible child interface for object:  PlacesView(0x7f9a4d21a0b0)  index:  12
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"
kf5.kio.core: couldn't create slave: "klauncher said: Unknown protocol 'file'.\n"

on gui display no files shown same as shared via issue #190

**Comment by yurikoles** [comment]
@two-dogs is it fixed in 18.08.0?

**Comment by two-dogs** [comment]
@yurikoles it is fixed yes, now if i could find a way to get to gdrive i would be really happy

**Comment by jcrben** [comment]
I'm running into this with Dolphin Version 18.12.3 (seems similar to https://github.com/KDE-mac/homebrew-kde/issues/250) but only when I ran it on the command-line:
![image](https://user-images.githubusercontent.com/5614134/54498733-e89ff680-48c7-11e9-8376-9a979a970346.png)

resulting in a Dolphin window without any files:
![image](https://user-images.githubusercontent.com/5614134/54498788-927f8300-48c8-11e9-9f58-7e1c37b2fe51.png)


If I run it with the Finder it works great.
