### ISSUE TITLE
error Installing okular from kde-mac/kde

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#258]
i am not sure where to search for a fix, i can provide more info on request.
perhaps related to issue https://github.com/KDE-mac/homebrew-kde/issues/225
actual error:
Already downloaded: /Users/emanuel/Library/Caches/Homebrew/okular--patch--33e5e0fa2a10fea2f11a1b975bfee3d87d80215aedb8013ea2d318818a250a46.diff
==> Patching
==> Applying patch-plugin-depends.diff
patching file mobile/components/CMakeLists.txt
Hunk #1 FAILED at 29.
1 out of 1 hunk FAILED -- saving rejects to file mobile/components/CMakeLists.txt.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/okular--patch-20180824-61591-zyrm3o/patch-plugin-depends.diff` exited with 1.

https://git.io/fAqKp

**Comment by yurikoles** [comment]
Hi @two-dogs,

Thanks for report, it seems that patch should be rebased or just removed. I don't have access to mac system now, I hope to fix it at Tuesday. 

P.S. For future use `brew gist-logs $fomula_name`

**Comment by babdulkarim** [comment]
@yurikoles any update on the fix?

**Comment by two-dogs** [comment]
@yurikoles thks sir, i have working okular
