### ISSUE TITLE
How can we install Dolphin on MacOS Mojave?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [KDE-mac/homebrew-kde#267]
Is there a tutorial that we can use to install Dolphin?

Dolphin is the best file manager by far =)

I'll be very glad to have it working on Mac too.

**Comment by yurikoles** [comment]
```
brew tap kde-mac/kde
"$(brew --repo)/Library/Taps/kde-mac/homebrew-kde/tools/all-fixes.sh"
brew install kde-mac/kde/dolphin
```

**Comment by brunorsini** [comment]
did this worked for you guys? got the following error on high sierra:

>  Summary
> 🍺  /usr/local/Cellar/libxslt/1.1.33_1: 137 files, 2.8MB
> ==> Installing kde-mac/kde/dolphin dependency: KDE-mac/kde/kf5-kdoctools
> ==> Downloading https://download.kde.org/stable/frameworks/5.58/kdoctools-5.58.0.tar.xz
> ==> Downloading from http://ftp.kddlabs.co.jp/pub/X11/kde/stable/frameworks/5.58/kdoctools-5.58.0.tar.xz
> ######################################################################## 100.0%
> ==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoc
> Last 15 lines from /Users/orsini/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
> -- Found Perl: /usr/local/bin/perl (found version "5.28.1")
> -- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND)
> CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find PerlModules (missing: PerlModules_all_modules_found
>   URI::Escape)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
>   cmake/uriencode.cmake:34 (find_package)
>   src/CMakeLists.txt:4 (kdoctools_encode_uri)

**Comment by Danilo-Araujo-Silva** [comment]
Unfortunately, I wasn't able to put Dolphin to work too =(

```
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)


-- Configuring incomplete, errors occurred!
```

**Comment by yurikoles** [comment]
@Danilo-Araujo-Silva 
The file was renamed, please run `"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"`

**Comment by KINGSABRI** [comment]
@ynakao 
The installation succeeds as I followed 
```
brew tap kde-mac/kde
"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
brew install kde-mac/kde/dolphin
```

Now how to run it? I can't find it using finder or using the terminal

**Comment by Danilo-Araujo-Silva** [comment]
I tried `$ /usr/local/opt/dolphin/bin/dolphin.app/Contents/MacOS/dolphin`

but I've received the following error:

```
dbus[24878]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
"Session bus not found\nTo circumvent this problem try the following command (with Linux and bash)\nexport $(dbus-launch)"
```

**Comment by Danilo-Araujo-Silva** [comment]
Going to `/usr/local/opt/dolphin/bin/` and opening the dolphin.app from finder it worked.
But unfortunately, the dolphin resolution is not too good. Can we do something about this?

**Comment by KINGSABRI** [comment]
Thanks @Danilo-Araujo-Silva 
but I got the same issue even with the suggested way
```
$/usr/local/opt/dolphin/bin/dolphin.app/Contents/MacOS/dolphin

dbus[70013]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
"Session bus not found\nTo circumvent this problem try the following command (with Linux and bash)\nexport $(dbus-launch)"
```

**Comment by Danilo-Araujo-Silva** [comment]
I can see my files (and their preview), but the scroll is not working properly, it looks like it only works when the scrollbar appears in the right.

**Comment by yurikoles** [comment]
Hi @Danilo-Araujo-Silva,

Thanks for your feedback. It will be nice if you could report your feedback in separate tickets for each upstream, https://bugs.kde.org/ 

Or if you have difficults, just write them here. Please don't forget to include exact macOS version and screenshots. Screenshots may be added by drag-and-drop on comment box. Thanks in advance! Let's do this software better together!

Or
