### ISSUE TITLE
fail to build kf5-solid

### ISSUE THREAD

**Issue by wicast** [KDE-mac/homebrew-kde#282]
I get this error:
```
/tmp/kf5-solid-20190311-85607-1ru2yiq/solid-5.56.0/src/solid/devices/backends/iokit/cfhelper.cpp:97:12: error: no member named 'setTime_t' in 'QDateTime'
        dt.setTime_t(uint(kCFAbsoluteTimeIntervalSince1970));
        ~~ ^
```

**Comment by two-dogs** [comment]
==> Upgrading kde-mac/kde/libkomparediff2
==> Installing dependencies for kde-mac/kde/libkomparediff2: KDE-mac/kde/kf5-solid and KDE-mac/kde/kf5-kio
==> Installing kde-mac/kde/libkomparediff2 dependency: KDE-mac/kde/kf5-solid
==> Downloading https://download.kde.org/stable/frameworks/5.56/solid-5.56.0.tar.xz
Already downloaded: /Users/emanuel/Library/Caches/Homebrew/downloads/6a6405ca5e06c974fc3614ae503dfae6748adc9c0e7c5e1b01085463e1328c69--solid-5.56.0.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-solid/5.56.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND
==> make install
Last 15 lines from /Users/emanuel/Library/Logs/Homebrew/kf5-solid/02.make:
        ~~ ^
1 error generated.
/tmp/kf5-solid-20190312-70941-1tuibtn/solid-5.56.0/src/solid/devices/backends/iokit/cfhelper.cpp:97:12: error: no member named 'setTime_t' in 'QDateTime'
        dt.setTime_t(uint(kCFAbsoluteTimeIntervalSince1970));
        ~~ ^
make[2]: *** [src/solid/CMakeFiles/KF5Solid.dir/devices/backends/iokit/cfhelper.cpp.o] Error 1
make[1]: *** [src/solid/CMakeFiles/KF5Solid.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by yurikoles** [comment]
Reported upstream: https://bugs.kde.org/show_bug.cgi?id=405554

**Comment by yurikoles** [comment]
https://bugs.kde.org/show_bug.cgi?id=405555

**Comment by wicast** [comment]
I've successfully build it with ```-DQT_DISABLE_DEPRECATED_BEFORE=0x000000``` flag

**Comment by sl1pkn07** [comment]
@wicast can you provide a link with the info about this?

greetings

**Comment by wicast** [comment]
The function is under QT_DEPRECATED_SINCE macro, so I override it and enable all deprecated functions.
https://doc.qt.io/qt-5/qtglobal.html#QT_DISABLE_DEPRECATED_BEFORE
https://github.com/qt/qtbase/blob/5.12/src/corelib/tools/qdatetime.cpp#L3784

**Comment by sl1pkn07** [comment]
not work for me

this
-DQT_DISABLE_DEPRECATED_BEFORE=0x000000
or this
-DQT_DISABLE_DEPRECATED_BEFORE="0x000000"

**Comment by wicast** [comment]
@sl1pkn07 try this code?

```
class Kf5Solid < Formula
  desc "Hardware integration and detection"
  homepage "https://www.kde.org"
  url "https://download.kde.org/stable/frameworks/5.56/solid-5.56.0.tar.xz"
  sha256 "841d90346cdc51214076cf26357701781d8d534dd209d92768f306e281e46e9e"

  revision 1
  head "git://anongit.kde.org/solid.git"

  depends_on "bison" => :build
  depends_on "cmake" => :build
  depends_on "doxygen" => :build
  depends_on "flex" => :build
  depends_on "graphviz" => :build
  depends_on "KDE-mac/kde/kf5-extra-cmake-modules" => :build
  depends_on "ninja" => :build

  depends_on "qt"

  def install
    args = std_cmake_args
    args << "-DBUILD_TESTING=OFF"
    args << "-DBUILD_QCH=ON"
    args << "-DKDE_INSTALL_QMLDIR=lib/qt5/qml"
    args << "-DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins"
    args << "-DQT_DISABLE_DEPRECATED_BEFORE=0x000000"
    args << "-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DQT_DISABLE_DEPRECATED_BEFORE=0x000000"
    args << "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DQT_DISABLE_DEPRECATED_BEFORE=0x000000"

    mkdir "build" do
      system "cmake", "-G", "Ninja", "..", *args
      system "ninja"
      system "ninja", "install"
      prefix.install "install_manifest.txt"
    end
  end
end
```

**Comment by sl1pkn07** [comment]
no XD. directly into cmake args xd

**Comment by sl1pkn07** [comment]
fixed. spit tons of warnings. but.. dunno

greetings
