### ISSUE TITLE
Question about D-Bus installation

### ISSUE THREAD

**Issue by wtanksleyjr** [KDE-mac/homebrew-kde#283]
The initial readme seems very clear, unless this is the first time I've installed D-Bus. I'm guessing that I need to, but the document doesn't make that clear, and it doesn't give any hint I can see about how to do it.

"Note: Read the D-Bus notes below if this is your first D-Bus installation."

I think it is...

"Follow the description in the D-Bus formula to set up the LaunchAgent."

What does that mean? Where do I go to find a D-Bus formula?

**Comment by yurikoles** [comment]
@wtanksleyjr you may ignore, I had removed it from readme, since it's very outdated, dbus works fine for a while.
