### ISSUE TITLE
kf5-solid build failure

### ISSUE THREAD

**Issue by yalok** [KDE-mac/homebrew-kde#284]
This is the error I get:
```
==> Installing kde-mac/kde/konsole dependency: KDE-mac/kde/kf5-solid
==> Downloading https://download.kde.org/stable/frameworks/5.56/solid-5.56.0.tar.xz
==> Downloading from http://ftp.cc.uoc.gr/mirrors/kde/stable/frameworks/5.56/solid-5.56.0.tar.xz
######################################################################## 100.0%
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/k
==> ninja
Last 15 lines from /Users/username/Library/Logs/Homebrew/kf5-solid/02.ninja:
In file included from src/solid/solid/device.h:1:
/tmp/kf5-solid-20190314-80466-1ec7pbl/solid-5.56.0/src/solid/devices/frontend/device.h:32:10: warning: non-portable path to file '<Solid/deviceinterface.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <solid/deviceinterface.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         <Solid/deviceinterface.h>
In file included from ../src/solid/devices/backends/iokit/iokitbattery.cpp:22:
In file included from ../src/solid/devices/backends/iokit/iokitbattery.h:25:
In file included from ../src/solid/devices/backends/iokit/iokitdeviceinterface.h:26:
In file included from ../src/solid/devices/backends/iokit/iokitdevice.h:24:
../src/solid/../solid/devices/ifaces/device.h:31:10: warning: non-portable path to file '<Solid/solidnamespace.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <solid/solidnamespace.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
         <Solid/solidnamespace.h>
6 warnings generated.
ninja: build stopped: subcommand failed.
```

**Comment by two-dogs** [comment]
@yalok, also reported here https://github.com/KDE-mac/homebrew-kde/issues/282

**Comment by two-dogs** [comment]
Last 15 lines from /Users/username/Library/Logs/Homebrew/kf5-solid/02.ninja:
In file included from ../src/solid/../solid/devices/ifaces/device.h:30:
In file included from src/solid/solid/device.h:1:
/tmp/kf5-solid-20190315-28119-aafgfk/solid-5.56.0/src/solid/devices/frontend/device.h:32:10: warning: non-portable path to file '<Solid/deviceinterface.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <solid/deviceinterface.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         <Solid/deviceinterface.h>
In file included from ../src/solid/devices/backends/iokit/iokitdeviceinterface.cpp:22:
In file included from ../src/solid/devices/backends/iokit/iokitdeviceinterface.h:26:
In file included from ../src/solid/devices/backends/iokit/iokitdevice.h:24:
../src/solid/../solid/devices/ifaces/device.h:31:10: warning: non-portable path to file '<Solid/solidnamespace.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <solid/solidnamespace.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
         <Solid/solidnamespace.h>
4 warnings generated.
ninja: build stopped: subcommand failed.

**Comment by yurikoles** [comment]
Those are warnings. Please share a link from `brew gist-logs kf5-solid`.

**Comment by josereyesjrz** [comment]
> Those are warnings. Please share a link from `brew gist-logs kf5-solid`.

Here is mine:
https://gist.github.com/josereyesjrz/5002c424935e69cd33c9a2e55e015262

**Comment by yurikoles** [comment]
Duplicates #282

**Comment by yurikoles** [comment]
Reported upstream: https://bugs.kde.org/show_bug.cgi?id=405554
