### ISSUE TITLE
kf5-kdewebkit errors occurred

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#287]

**Comment by two-dogs** [comment]
brew gist-logs kf5-kdewebkit
https://gist.github.com/02736045d16d3f844eedb28819742fa1

**Comment by sl1pkn07** [comment]
seems you need reinstall qt-webkit

is needs rebuild if a newer version of Qt is installed

**Comment by two-dogs** [comment]
@sl1pkn07  i'll give that a try, thnks

**Comment by two-dogs** [comment]
kde-mac/kde/qt-webkit 5.212.0-alpha2_3 already installed, would not upgrade any further.

**Comment by sl1pkn07** [comment]
`brew reinstall qt-webkit`

**Comment by two-dogs** [comment]
@sl1pkn07

==> cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qt-webkit/5.212.0-alpha2_3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-de
==> ninja

==> ninja install
🍺  /usr/local/Cellar/qt-webkit/5.212.0-alpha2_3: 143 files, 46.2MB, built in 139 minutes 33 seconds

**Comment by yurikoles** [comment]
@two-dogs is it resolved for you?

**Comment by sl1pkn07** [comment]
@yurikoles any option in the qt-webkit formula for prevent the Qt upgrade if reach a certain version of Qt?

like do makepkg/pacman in archlinux if set `depends=('package>=version')`

**Comment by yurikoles** [comment]
@sl1pkn07 the easiest way is to bump `qt-webkit` revision on every release of `qt`.

**Comment by yurikoles** [comment]
See 472b243ecb82c8acf20b4daffad04d73e5507e0e.
