### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by surrutiaquir** [KDE-mac/homebrew-kde#289]
If you try to use the suggested line to uninstall all packages,

`brew uninstall brew list --full-name -1 | grep '^kde-mac/kde'`

You get the following error:

`brew uninstall, rm, remove [--force] [--ignore-dependencies] formula:`
`    Uninstall formula.`

`    If --force (or -f) is passed, and there are multiple versions of formula`
`    installed, delete all installed versions.`

`    If --ignore-dependencies is passed, uninstalling won't fail, even if`
`    formulae depending on formula would still be installed.`

`Error: Invalid usage: This command requires a keg argument`

**Comment by sl1pkn07** [comment]
Can you edit the post? Seems github eating characters when use the ` markup

Greetings

**Comment by surrutiaquir** [comment]
I don't know how to fix it, so this is what I got

**Comment by yurikoles** [comment]
It seems like ` is missing in your command. You should invoke:
```
brew uninstall `brew list --full-name -1 | grep '^kde-mac/kde'`
```

**Comment by surrutiaquir** [comment]
I tried that way, and I'm still getting the same error.
Thank you anyway

**Comment by yurikoles** [comment]
Please try `brew list --full-name -1 | grep '^kde-mac/kde' | xargs brew uninstall`

**Comment by yurikoles** [comment]
Or `brew uninstall -f "$(brew --repo kde-mac/kde)"/Formula/*.rb`

**Comment by sl1pkn07** [comment]
instead of use \` for the comments, better use ~~~, using \` in this case breaks the syntax

**Comment by surrutiaquir** [comment]
Thank you @yurikoles, your first suggestion worked perfectly!
