### ISSUE TITLE
kde-mac/kde/elisa fails build on mac high sierra

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#290]
Undefined symbols for architecture x86_64:
  "AudioWrapper::saveUndoPosition(long long)", referenced from:
      ElisaApplication::initializePlayer() in elisaapplication.cpp.o
      AudioWrapper::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in audiowrapper_qtmultimedia.cpp.o
  "AudioWrapper::restoreUndoPosition()", referenced from:
      ElisaApplication::initializePlayer() in elisaapplication.cpp.o
      AudioWrapper::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in audiowrapper_qtmultimedia.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libelisaLib.0.1.dylib] Error 1
make[1]: *** [src/CMakeFiles/elisaLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by yurikoles** [comment]
@two-dogs please report [upstream](https://bugs.kde.org/)

**Comment by yurikoles** [comment]
Also, please run `brew gist-logs elisa` and give us url to gist.

**Comment by two-dogs** [comment]
brew gist-logs elisa

https://gist.github.com/8cfc4271982e3fc1cb2725cb3f2c0178

**Comment by yurikoles** [comment]
Upstream: https://bugs.kde.org/show_bug.cgi?id=406499

**Comment by sl1pkn07** [comment]
https://github.com/KDE-mac/homebrew-kde/tree/elisa please test

**Comment by two-dogs** [comment]
@sl1pkn07 , i see follow caveats;
==> kf5-knotifications
You need to take some manual steps in order to make this formula work:
  ln -sfv "$(brew --prefix)/share/kservicetypes5" "$HOME/Library/Application Support"
==> kf5-kio
You need to take some manual steps in order to make this formula work:
  ln -sfv "$(brew --prefix)/share/kf5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/knotifications5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservicetypes5" "$HOME/Library/Application Support"
==> elisa
You need to take some manual steps in order to make this formula work:
  ln -sfv "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/metainfo" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kpackage "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/icons" "$HOME/Library/Application Support"
  mkdir -pv "$HOME/Applications/KDE"
  ln -sfv "$(brew --prefix)/opt/elisa/bin/elisa.app" "$HOME/Applications/KDE/"

and on executing caveats specific to elisa i get ; 
https://git.io/fjZjU
'>' at this point return does nothing , unsure what to enter so in each case i ctrl-c out

app icon does not show in Launchpad, does show in KDE apps folder, click start shows app icon on dock with no gui on desktop, closing app from dock works.

**Comment by sl1pkn07** [comment]
please paste the contents of you `/usr/local/lib/plugin` `/usr/local/lib/qml` and `/usr/local/lib/qt5`

**Comment by two-dogs** [comment]
@sl1pkn07 ,  dolphin now wont start, i started both elisa and dolphin from command line and i saw errors specific to dbus , i restarted dbus service, i saw a positive reply to dbus started via brew services start dbus, and i did find dbus service stopped when i first checked when i first saw error.
my guess is something changed on last brew update with install of elisa. 

i did following with positive result, dolphin started;
brew remove elisa
brew reinstall dbus qt kde-mac/kde/kf5-kdbusaddons dolphin 
brew services start dbus
started dolphin from Launchpad

**Comment by two-dogs** [comment]
https://git.io/fjZju    /usr/local/lib/plugins

https://git.io/fjZjz   /usr/local/lib/qml

https://git.io/fjZj2   /usr/local/lib/qt5/{qml,plugins}

**Comment by sl1pkn07** [comment]
ok, seems you have the installation in mixed paths. let me time to upgrade the elisa branch

**Comment by two-dogs** [comment]
i would call this one fixed
