### ISSUE TITLE
kde-mac/kde/kio-extras

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#294]
# Please specify exact formula that has issue

<!kde-mac/kde/kio-extras>

# What happened (include command output)

<!==> Upgrading kde-mac/kde/kio-extras
==> Downloading https://download.kde.org/stable/applications/19.04.0/src/kio-extras-19.04.0.tar.xz
==> Downloading from http://ftp.ussg.iu.edu/kde/stable/applications/19.04.0/src/kio-extras-19.04.0.tar.xz
######################################################################## 100.0%
==> Patching
patching file network/mimetypes/CMakeLists.txt
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file network/mimetypes/CMakeLists.txt.rej
patching file mtp/kiod_module/mtpstorage.cpp
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
1232

**Comment by yurikoles** [comment]
@two-dogs it seems like patch needs to be either re-based or removed.
Could you try building with commenting-out patch?

**Comment by yurikoles** [comment]
@two-dogs fixed in 42bc766bc63e8e2fbabce3abef38fc4dd12cc03e

**Comment by two-dogs** [comment]
@yurikoles , looking at the template for error reporting using gist-log the command should be 'brew gist-logs ...' , took me a while to figure out why i kept hitting a command not found error.

**Comment by yurikoles** [comment]
@two-dogs fixed in 0f1f0d1bcf124613b324fdc2cdfd28c59009e903
