### ISSUE TITLE
kcalc fails to build - "missing: Init XmlGui"

### ISSUE THREAD

**Issue by rikkus** [KDE-mac/homebrew-kde#297]
# Please specify exact formula that has issue

kcalc

# What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Installing kcalc from kde-mac/kde
==> Downloading https://download.kde.org/stable/applications/19.04.0/src/kcalc-1
Already downloaded: /Users/rhemsley/Library/Caches/Homebrew/downloads/0eeb046d308fb14b81b831817c7f7e4f4312697488db348ccfecc1db42b6899c--kcalc-19.04.0.tar.xz
==> Patching
patching file CMakeLists.txt
Hunk #1 succeeded at 125 (offset 2 lines).
patching file MacOSXBundleInfo.plist.in
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE
Last 15 lines from /Users/rhemsley/Library/Logs/Homebrew/kcalc/01.cmake:
-- Found KF5Notifications: /usr/local/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.57.0") 
-- Could NOT find KF5XmlGui (missing: KF5XmlGui_DIR)
-- Could NOT find KF5XmlGui: found neither KF5XmlGuiConfig.cmake nor kf5xmlgui-config.cmake 
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Init XmlGui) (found suitable version "5.57.0",
  minimum required is "5.46.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:34 (find_package) </pre>
</details>

# URL to gist, invoke `brew gist-logs <failed-formula>`

https://gist.github.com/70dc0baa7d2a1ba0da8dbfeb08a890fc

**Comment by sl1pkn07** [comment]
Thanks for the report

@rikkus can you try now?

greetings

**Comment by sl1pkn07** [comment]
@rikkus ping?

**Comment by rikkus** [comment]
It worked! Thanks a lot
