### ISSUE TITLE
kio-extra can not be compiled and okular cannot launch due to that

### ISSUE THREAD

**Issue by sudoyang** [KDE-mac/homebrew-kde#298]
# Please specify exact formula that has issue

kde-mac/kde/kio-extras

# What happened (include command output)

CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SharedMimeInfo (missing: UPDATE_MIME_DATABASE_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindSharedMimeInfo.cmake:74 (find_package_handle_standard_args)
  network/mimetypes/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/kio-extras-20190504-95905-1bldjph/kio-extras-19.04.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kio-extras-20190504-95905-1bldjph/kio-extras-19.04.0/build/CMakeFiles/CMakeError.log".

<details>
  <summary>Command output</summary>
  <pre>
  
?  ~ brew update && brew upgrade && brew cleanup
Already up-to-date.
==> Upgrading 1 outdated package:
kde-mac/kde/kio-extras 19.04.0_1
==> Upgrading kde-mac/kde/kio-extras
==> Downloading https://download.kde.org/stable/applications/19.04.0/src/kio-extras-19.04.0.tar.xz
Already downloaded: /Users/godel/Library/Caches/Homebrew/downloads/9bed04b07b1d7e257a513614561b4f0efe8f058c2b69e09e7d7258aff6d370b4--kio-extras-19.04.0.tar.xz
==> Patching
patching file mtp/kiod_module/mtpstorage.cpp
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/lo
Last 15 lines from /Users/godel/Library/Logs/Homebrew/kio-extras/01.cmake:
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SharedMimeInfo (missing: UPDATE_MIME_DATABASE_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindSharedMimeInfo.cmake:74 (find_package_handle_standard_args)
  network/mimetypes/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/kio-extras-20190504-95905-1bldjph/kio-extras-19.04.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kio-extras-20190504-95905-1bldjph/kio-extras-19.04.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kde-mac/homebrew-kde/issues

  
  </pre>
</details>

# URL to gist, invoke `brew gist-logs <failed-formula>`

**Comment by sl1pkn07** [comment]
@sudoyang try now

**Comment by sudoyang** [comment]
@sl1pkn07  Thanks! Everything is back to normal.
