### ISSUE TITLE
[FR] Add hook to Mirror to GitLab for better free CI

### ISSUE THREAD

**Issue by yurikoles** [KDE-mac/homebrew-kde#306]
It seems like GitLab has some public CI runners, that may run build for about one hour.

So I think we should add some hook to auto-update GitLab mirror and add GitLab CI config.

Ping @sl1pkn07.

**Comment by sl1pkn07** [comment]
build qt-webkit takes long long.................long......long..... time...., i'm not sure if with one hour is sufficient (what hardware and num of threads use the gitlab CI?)

about the gitlab mirror, i don't have any idea how do it, you know it?

**Comment by yurikoles** [comment]
Oh, there is no public mac machines.
