### ISSUE TITLE
Remove cyrus-sasl

### ISSUE THREAD

**Issue by sl1pkn07** [KDE-mac/homebrew-kde#307]
cyrus-sasl now is orphan (no needed by other formula) and is not a KDE library

remove it?

@yurikoles

**Comment by yurikoles** [comment]
@sl1pkn07 so let's just remove it.

**Comment by sl1pkn07** [comment]
done in https://github.com/KDE-mac/homebrew-kde/commit/a0ed8331bc1d4310369e8ba97aebcb2c533f76c9
