### ISSUE TITLE
Could kf5-kdoctools be made optional ?

### ISSUE THREAD

**Issue by mathieujobin** [KDE-mac/homebrew-kde#311]
# Please specify exact formula that has issue

kf5-kdoctools

# What happened (include command output)

I am getting a compile error, and my feeling is that I might not need this dependency at all

in anycase, here is the output

<details>
  <summary>Command output</summary>
  <pre>
  
bash-3.2$ brew install kde-mac/kde/kate
==> Installing kate from kde-mac/kde
==> Installing dependencies for kde-mac/kde/kate: KDE-mac/kde/kf5-kdoctools, KDE-mac/kde/kf5-kconfig, KDE-mac/kde/kf5-kcoreaddons, KDE-mac/kde/kf5-kwindowsystem, KDE-mac/kde/kf5-kactivities, KDE-mac/kde/kf5-attica, KDE-mac/kde/kf5-kcrash, KDE-mac/kde/kf5-kdbusaddons, KDE-mac/kde/kf5-kglobalaccel, KDE-mac/kde/kf5-kwidgetsaddons, KDE-mac/kde/kf5-kcompletion, KDE-mac/kde/kf5-kauth, KDE-mac/kde/kf5-kcodecs, KDE-mac/kde/kf5-kguiaddons, KDE-mac/kde/kf5-kconfigwidgets, KDE-mac/kde/kf5-kitemviews, KDE-mac/kde/kf5-kiconthemes, KDE-mac/kde/kf5-kservice, KDE-mac/kde/kf5-sonnet, KDE-mac/kde/kf5-ktextwidgets, KDE-mac/kde/kf5-kxmlgui, KDE-mac/kde/kf5-kbookmarks, KDE-mac/kde/kf5-kjobwidgets, KDE-mac/kde/phonon, KDE-mac/kde/kf5-knotifications, KDE-mac/kde/kf5-kwallet, KDE-mac/kde/kf5-solid, KDE-mac/kde/kf5-kio, KDE-mac/kde/kf5-kpackage, KDE-mac/kde/kf5-kdeclarative, KDE-mac/kde/kf5-kirigami2, KDE-mac/kde/kf5-plasma-framework, KDE-mac/kde/kf5-breeze-icons, KDE-mac/kde/kf5-kitemmodels, KDE-mac/kde/kf5-knewstuff, KDE-mac/kde/kf5-kparts, KDE-mac/kde/kf5-syntax-highlighting, KDE-mac/kde/kf5-ktexteditor and KDE-mac/kde/kf5-threadweaver
==> Installing kde-mac/kde/kate dependency: KDE-mac/kde/kf5-kdoctools
==> Downloading https://download.kde.org/stable/frameworks/5.58/kdoctools-5.58.0.tar.xz
Already downloaded: /Users/mac61/Library/Caches/Homebrew/downloads/71965c6a8a4455c28ef7dd6625a9a26a80a815519c0e458c1403796ac9f999bd--kdoctools-5.58.0.tar.xz
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoctools/5.58.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LA
Last 15 lines from /Users/mac61/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.28.1")
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND)
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)

-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20190517-79238-1644w6c/kdoctools-5.58.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20190517-79238-1644w6c/kdoctools-5.58.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kde-mac/homebrew-kde/issues

These open issues may also help:
kde-mac/kde/kf5-kdoctools installation fails on Mac OS X Sierra https://github.com/KDE-mac/homebrew-kde/issues/293
bash-3.2$  
  </pre>
</details>

# URL to gist, invoke `brew gist-logs <failed-formula>`

**Comment by sl1pkn07** [comment]
Run tools/do-caveats.sh and try again

**Comment by mathieujobin** [comment]
Thank you, it worked

**Comment by samcmac133** [comment]
I've been trying to figure out how to solve the "missing: PerlModules_all_modules_found URI::Escape" issue that I'm having for going on 3 days now, carefully combing through all the various fixes I've come across on this site from those who are also having issues with the the kdoctools section of the kde build. I'm really new to this stuff though, so I must be missing something. I'm attaching my most recent log, which includes the running tools/do-caveats.sh, but that still didn't help. Anyone have ideas? If you need more info from me just let me know. Thanks.

[Terminal Saved Output.txt](https://github.com/KDE-mac/homebrew-kde/files/3301348/Terminal.Saved.Output.txt)

also pasted here:

Last login: Tue Jun 18 07:34:03 on ttys000
Sams-iMac:~ samcmac$ brew install kde-mac/kde/kf5-kdoctools
==> Installing kf5-kdoctools from kde-mac/kde
==> Downloading https://download.kde.org/stable/frameworks/5.59/kdoctools-5.59.0.tar.xz
Already downloaded: /Users/samcmac/Library/Caches/Homebrew/downloads/7f0d970e8690a3d4165ace90e5a6849e00c2be7d2015d89553e03103f1c12cac--kdoctools-5.59.0.tar.xz
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoctools/5.59.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DBUILD_
Last 15 lines from /Users/samcmac/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.30.0") 
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)


-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20190618-48461-j3v9bo/kdoctools-5.59.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20190618-48461-j3v9bo/kdoctools-5.59.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kde-mac/homebrew-kde/issues

These open issues may also help:
kde-mac/kde/kf5-kdoctools installation fails on Mac OS X Sierra https://github.com/KDE-mac/homebrew-kde/issues/293
Sams-iMac:~ samcmac$ /Users/samcmac/homebrew-kde-master/tools/do-caveats.sh 
Warning: perl 5.30.0 is already installed and up-to-date
To reinstall 5.30.0, run `brew reinstall perl`
Warning: dbus 1.12.12 is already installed and up-to-date
To reinstall 1.12.12, run `brew reinstall dbus`
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/Users/samcmac/.cpan/Metadata'
  Database was generated on Mon, 17 Jun 2019 13:41:03 GMT
CPAN: Module::CoreList loaded ok (v5.20180622)
CPAN is up to date (2.26).
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/Users/samcmac/.cpan/Metadata'
  Database was generated on Mon, 17 Jun 2019 13:41:03 GMT
CPAN: Module::CoreList loaded ok (v5.20180622)
URI is up to date (1.76).
URI::Escape is up to date (3.31).
Service `dbus` already started, use `brew services restart dbus` to restart.
/Users/samcmac/Library/Application Support/doc/HTML -> /usr/local/share/doc/HTML
/Users/samcmac/Library/Application Support/doc/qch -> /usr/local/share/doc/qch
/Users/samcmac/Library/Application Support/kf5 -> /usr/local/share/kf5
/Users/samcmac/Library/Application Support/kservices5 -> /usr/local/share/kservices5
/Users/samcmac/Library/Application Support/metainfo -> /usr/local/share/metainfo
/Users/samcmac/Library/Application Support/kservicetypes5 -> /usr/local/share/kservicetypes5
/Users/samcmac/Library/Application Support/config.kcfg -> /usr/local/share/config.kcfg
/Users/samcmac/Library/Application Support/knotifycations5 -> /usr/local/share/knotifycations5
/Users/samcmac/Library/Application Support/kxmlgui5 -> /usr/local/share/kxmlgui5
/Users/samcmac/Library/Application Support/kpackage -> /usr/local/share/kpackage
/Users/samcmac/Library/Application Support/icons -> /usr/local/share/icons
/Users/samcmac/Library/Application Support/emoticons -> /usr/local/share/emoticons
/Users/samcmac/Library/Application Support/kdevappwizard -> /usr/local/share/kdevappwizard
/Users/samcmac/Applications/KDE/kdebugdialog5.app -> /usr/local/opt/kf5-kdelibs4support/bin/kdebugdialog5.app
/Users/samcmac/Library/Application Support/plasma -> /usr/local/share/plasma
/Users/samcmac/Library/Application Support/dolphin -> /usr/local/share/dolphin
/Users/samcmac/Applications/KDE/dolphin.app -> /usr/local/opt/dolphin/bin/dolphin.app
/Users/samcmac/Library/Application Support/kate -> /usr/local/share/kate
/Users/samcmac/Library/Application Support/kwrite -> /usr/local/share/kwrite
/Users/samcmac/Library/Application Support/kateproject -> /usr/local/share/kateproject
/Users/samcmac/Library/Application Support/katexmltools -> /usr/local/share/katexmltools
/Users/samcmac/Applications/KDE/kate.app -> /usr/local/opt/kate/bin/kate.app
/Users/samcmac/Applications/KDE/kwrite.app -> /usr/local/opt/kate/bin/kwrite.app
/Users/samcmac/Library/Application Support/kio_bookmarks -> /usr/local/share/kio_bookmarks
/Users/samcmac/Library/Application Support/kio_info -> /usr/local/share/kio_info
/Users/samcmac/Library/Application Support/konqsidebartng -> /usr/local/share/konqsidebartng
/Users/samcmac/Library/Application Support/konqueror -> /usr/local/share/konqueror
/Users/samcmac/Library/Application Support/remoteview -> /usr/local/share/remoteview
/Users/samcmac/Library/Application Support/solid -> /usr/local/share/solid
/Users/samcmac/Library/Application Support/kmymoney -> /usr/local/share/kmymoney
/Users/samcmac/Library/Application Support/kmm_weboob -> /usr/local/share/kmm_weboob
/Users/samcmac/Library/Application Support/kmm_printcheck -> /usr/local/share/kmm_printcheck
/Users/samcmac/Applications/KDE/kmymoney.app -> /usr/local/opt/kmymoney/bin/kmymoney.app
/Users/samcmac/Library/Application Support/kolourpaint -> /usr/local/share/kolourpaint
/Users/samcmac/Applications/KDE/kolourpaint.app -> /usr/local/opt/kolourpaint/bin/kolourpaint.app
/Users/samcmac/Library/Application Support/konsole -> /usr/local/share/konsole
/Users/samcmac/Applications/KDE/konsole.app -> /usr/local/opt/konsole/bin/konsole.app
/Users/samcmac/Library/Application Support/konversation -> /usr/local/share/konversation
/Users/samcmac/Applications/KDE/konversation.app -> /usr/local/opt/konversation/bin/konversation.app
/Users/samcmac/Applications/KDE/lokalize.app -> /usr/local/opt/lokalize/bin/lokalize.app
/Users/samcmac/Library/Application Support/okteta -> /usr/local/share/okteta
/Users/samcmac/Applications/KDE/okteta.app -> /usr/local/opt/okteta/bin/okteta.app
/Users/samcmac/Library/Application Support/kdevappwizard -> /usr/local/share/kdevappwizard
/Users/samcmac/Library/Application Support/kdevclangsupport -> /usr/local/share/kdevclangsupport
/Users/samcmac/Library/Application Support/kdevcodeutils -> /usr/local/share/kdevcodeutils
/Users/samcmac/Library/Application Support/kdevelop -> /usr/local/share/kdevelop
/Users/samcmac/Library/Application Support/kdevfiletemplates -> /usr/local/share/kdevfiletemplates
/Users/samcmac/Library/Application Support/kdevgdb -> /usr/local/share/kdevgdb
/Users/samcmac/Library/Application Support/kdevmanpage -> /usr/local/share/kdevmanpage
/Users/samcmac/Library/Application Support/kdevqmakebuilder -> /usr/local/share/kdevqmakebuilder
/Users/samcmac/Library/Application Support/kdevqmljssupport -> /usr/local/share/kdevqmljssupport
/Users/samcmac/Applications/KDE/kdevelop.app -> /usr/local/opt/kdevelop/bin/kdevelop.app
/Users/samcmac/Library/Application Support/okular -> /usr/local/share/okular
/Users/samcmac/Applications/KDE/okular.app -> /usr/local/opt/okular/bin/okular.app
/Users/samcmac/Applications/KDE/okularkirigami.app -> /usr/local/opt/okular/bin/okularkirigami.app
/Users/samcmac/Library/Application Support/labplot2 -> /usr/local/share/labplot2
/Users/samcmac/Applications/KDE/labplot2.app -> /usr/local/opt/labplot/bin/labplot2.app
/Users/samcmac/Library/Application Support/kdenlive -> /usr/local/share/kdenlive
/Users/samcmac/Applications/KDE/kdenlive.app -> /usr/local/opt/kdenlive/bin/kdenlive.app
/Users/samcmac/Library/Application Support/krename -> /usr/local/share/krename
/Users/samcmac/Applications/KDE/krename.app -> /usr/local/opt/krename/bin/krename.app
/Users/samcmac/Library/Application Support/ktorrent -> /usr/local/share/ktorrent
/Users/samcmac/Applications/KDE/ktorrent.app -> /usr/local/opt/ktorrent/bin/ktorrent.app
/Users/samcmac/Applications/KDE/ktupnptest.app -> /usr/local/opt/ktorrent/bin/ktupnptest.app
/Users/samcmac/Library/Application Support/krusader -> /usr/local/share/krusader
/Users/samcmac/Applications/KDE/krusader.app -> /usr/local/opt/krusader/bin/krusader.app
/Users/samcmac/Applications/KDE/elisa.app -> /usr/local/opt/elisa/bin/elisa.app
/Users/samcmac/Library/Application Support/kcalc -> /usr/local/share/kcalc
/Users/samcmac/Applications/KDE/kcalc.app -> /usr/local/opt/kcalc/bin/kcalc.app
/Users/samcmac/Library/Application Support/ksysguard -> /usr/local/share/ksysguard
/Users/samcmac/Applications/KDE/ksysguard.app -> /usr/local/opt/ksysguard/bin/ksysguard.app
/Users/samcmac/Library/Application Support/umbrello5 -> /usr/local/share/umbrello5
/Users/samcmac/Applications/KDE/umbrello5.app -> /usr/local/opt/umbrello/bin/umbrello5.app
/Users/samcmac/Applications/KDE/AtCoreTest.app -> /usr/local/opt/atcore/bin/AtCoreTest.app
Sams-iMac:~ samcmac$ brew install kde-mac/kde/kf5-kdoctools
==> Installing kf5-kdoctools from kde-mac/kde
==> Downloading https://download.kde.org/stable/frameworks/5.59/kdoctools-5.59.0.tar.xz
Already downloaded: /Users/samcmac/Library/Caches/Homebrew/downloads/7f0d970e8690a3d4165ace90e5a6849e00c2be7d2015d89553e03103f1c12cac--kdoctools-5.59.0.tar.xz
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoctools/5.59.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DBUILD_
Last 15 lines from /Users/samcmac/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.30.0") 
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)


-- Configuring incomplete, errors occurred!
See also "/tmp/kf5-kdoctools-20190618-51491-173spj5/kdoctools-5.59.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/kf5-kdoctools-20190618-51491-173spj5/kdoctools-5.59.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kde-mac/homebrew-kde/issues

These open issues may also help:
kde-mac/kde/kf5-kdoctools installation fails on Mac OS X Sierra https://github.com/KDE-mac/homebrew-kde/issues/293
Sams-iMac:~ samcmac$
