### ISSUE TITLE
kf5-kdeclarative: file INSTALL cannot find KF5Declarative.qch

### ISSUE THREAD

**Issue by two-dogs** [KDE-mac/homebrew-kde#318]
# Please specify exact formula that has issue

kf5-kdeclarative/5.61.0

# What happened (include command output)

==> Upgrading kde-mac/kde/kf5-kdeclarative
==> Downloading https://download.kde.org/stable/frameworks/5.61/kdeclarative-5.61.0.tar.xz
Already downloaded: /Users/xxxxxxxx//Library/Caches/Homebrew/downloads/a68860c2fe623b47893579b1d7295a5003200b81ad06cf42f4cd9e146420ef19--kdeclarative-5.61.0.tar.xz
==> Patching
patching file CMakeLists.txt
Hunk #1 succeeded at 42 (offset -6 lines).
patching file src/kpackagelauncherqml/CMakeLists.txt
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdeclarative/5.61.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON
==> ninja
==> ninja install
Last 15 lines from /Users/emanuel/Library/Logs/Homebrew/kf5-kdeclarative/03.ninja:
-- Installing: /usr/local/Cellar/kf5-kdeclarative/5.61.0/lib/cmake/KF5Declarative/KF5DeclarativeConfig.cmake
-- Installing: /usr/local/Cellar/kf5-kdeclarative/5.61.0/lib/cmake/KF5Declarative/KF5DeclarativeConfigVersion.cmake
-- Installing: /usr/local/Cellar/kf5-kdeclarative/5.61.0/lib/cmake/KF5Declarative/KF5DeclarativeTargets.cmake
-- Installing: /usr/local/Cellar/kf5-kdeclarative/5.61.0/lib/cmake/KF5Declarative/KF5DeclarativeTargets-release.cmake
-- Installing: /usr/local/Cellar/kf5-kdeclarative/5.61.0/include/KF5/kdeclarative_version.h
CMake Error at src/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/tmp/kf5-kdeclarative-20190813-77190-1gnjhjg/kdeclarative-5.61.0/build/src/KF5Declarative.qch".
Call Stack (most recent call first):
  cmake_install.cmake:75 (include)

FAILED: CMakeFiles/install.util
cd /tmp/kf5-kdeclarative-20190813-77190-1gnjhjg/kdeclarative-5.61.0/build && /usr/local/Cellar/cmake/3.15.2/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.

# URL to gist, invoke `brew gist-logs <failed-formula>`

https://gist.github.com/9ad4cbb02f3f4469024b5ef0a369a8ba

**Comment by two-dogs** [comment]
I am not sure the issue is a classic 'bug' and I am clueless how to remove the tag.

**Comment by yurikoles** [comment]
@two-dogs yes, it's a bug, I see same issue on my machine

**Comment by yurikoles** [comment]
Could you please open a ticket [upstream](https://bugs.kde.org/)?

**Comment by two-dogs** [comment]
@yurikoles , if you already have an account with bugs.kde pls submit bug report.

**Comment by yurikoles** [comment]
@two-dogs https://bugs.kde.org/show_bug.cgi?id=410892
You may CC yourself even without account.

**Comment by yurikoles** [comment]
@krf @krrk @sl1pkn07 
Please look into this, because a lot of apps are broken due to this bug.

**Comment by two-dogs** [comment]
@yurikoles , kudos
