### ISSUE TITLE
can't build kf5-knotifications. warnings error

### ISSUE THREAD

**Issue by t3harvinator** [KDE-mac/homebrew-kde#326]
Hi,

I'm trying to install kf5-knotifications and I think it might have -Werror somewhere that is stopping it from building when these warnings are triggered. I'm not sure how to get it to build.

I am on Mac OS X High Sierra and have ran the do-caveats.sh script already.

Thanks for your time.

====================================
Updating Homebrew...
==> Installing kf5-knotifications from kde-mac/kde
==> Downloading https://download.kde.org/stable/frameworks/5.65/knotifications-5.65.0.tar.xz
Already downloaded: /Users/stones/Library/Caches/Homebrew/downloads/1c8e2dfd7215019e5792c74826749c7237f10b086dca5d3b6a8619e6dbaabc52--knotifications-5.65.0.tar.xz
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-knotifications/5.65.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DBUILD_QCH=ON -DKDE_INSTALL_QMLDIR=lib/qt5/qml -DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins -DKDE_INSTALL_QTPLUGINDIR=lib/qt5/plugins -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DQT_DISABLE_DEPRECATED_BEFORE=0x050b00 -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DQT_DISABLE_DEPRECATED_BEFORE=0x050b00
==> ninja
Last 15 lines from /Users/stones/Library/Logs/Homebrew/kf5-knotifications/02.ninja:
/usr/local/opt/qt/include/QtCore/qresultstore.h:161:38: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
            return addResults(index, 0, 0, totalCount);
                                     ^
                                     nullptr
In file included from src/notifications_interface.cpp:12:
In file included from src/notifications_interface.h:21:
In file included from /usr/local/opt/qt/include/QtDBus/QtDBus:3:
In file included from /usr/local/opt/qt/include/QtDBus/QtDBusDepends:3:
In file included from /usr/local/opt/qt/include/QtCore/QtCore:238:
/usr/local/opt/qt/lib/QtCore.framework/Headers/qthreadstorage.h:72:23: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
    if (!v) v = d.set(0);
                      ^
                      nullptr
2 warnings generated.
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/KDE-mac/homebrew-kde/issues

**Comment by yurikoles** [comment]
Please execute: `"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"` and try again.

**Comment by t3harvinator** [comment]
Thanks for the quick reply! That worked but I am getting another error now.

When trying to compile, it cannot find Appkit/Appkit.h.

I've tried having `usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++` symbolically linked to my xcode clang++ with `ln -s /Library/Developer/CommandLineTools/usr/bin/clang++ /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++` but that did not yield any results.

=============================
usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DHAVE_CANBERRA -DHAVE_SPEECH -DKCOREADDONS_LIB -DKF5Notifications_EXPORTS -DKF_DEPRECATED_WARNINGS_SINCE=0x060000 -DKF_DISABLE_DEPRECATED_BEFORE_AND_AT=0x053f00 -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_MAC_USE_COCOA -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_TEXTTOSPEECH_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -Isrc -I../src -Isrc/KF5Notifications_autogen/include -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -isystem /usr/local/include/KF5/KCoreAddons -isystem /usr/local/include/KF5 -isystem /usr/local/include/KF5/KConfigCore -isystem /usr/local/include/KF5/KWindowSystem -isystem /usr/local/include/KF5/KCodecs -isystem /usr/local/opt/qt/lib/QtTextToSpeech.framework/Headers -isystem /usr/local/opt/qt/lib/QtMacExtras.framework/Headers -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant -DNDEBUG -DQT_DISABLE_DEPRECATED_BEFORE=0x050b00 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -D_REENTRANT -I/usr/local/Cellar/libcanberra/0.30/include -std=gnu++11 -MD -MT src/CMakeFiles/KF5Notifications.dir/notifybymacosnotificationcenter.mm.o -MF src/CMakeFiles/KF5Notifications.dir/notifybymacosnotificationcenter.mm.o.d -o src/CMakeFiles/KF5Notifications.dir/notifybymacosnotificationcenter.mm.o -c ../src/notifybymacosnotificationcenter.mm
../src/notifybymacosnotificationcenter.mm:10:9: fatal error: 'Appkit/Appkit.h' file not found
#import <Appkit/Appkit.h>
        ^~~~~~~~~~~~~~~~~
1 error generated.
[129/133] Building CXX object src/CMakeFiles/KF5Notifications.dir/statusnotifieritemadaptor.cpp.o
[130/133] Building CXX object src/CMakeFiles/KF5Notifications.dir/statusnotifierwatcher_interface.cpp.o
[131/133] Building CXX object src/CMakeFiles/KF5Notifications.dir/notifications_interface.cpp.o
ninja: build stopped: subcommand failed.

**Comment by t3harvinator** [comment]
hmm...it appears that if I change it to `AppKit/AppKit.h` it works. typo?

**Comment by yurikoles** [comment]
I'm not sure why you have this problem, it works for me.

**Comment by t3harvinator** [comment]
I think it's because I was dumb and made my mac a case sensitive operating system.

**Comment by yurikoles** [comment]
Ok, it should be reported anyway. Don't you mind reporting [upstream](https://bugs.kde.org/)?

**Comment by yurikoles** [comment]
Leave comment here if you face any difficulties. Please also try to test as many formulas as you can, since I need to reformat my disk to reproduce it.

**Comment by t3harvinator** [comment]
Thanks for the help! I reported it and changed the src code to the correct case as a test in `src/notifybymacosnotificationcenter.mm` and it built fine.
I'll report any other issues I run into.

https://bugs.kde.org/show_bug.cgi?id=415215

**Comment by yurikoles** [comment]
Thanks @t3harvinator,

Could you please test other formulas as well?

**Comment by t3harvinator** [comment]
I just built all the dependencies for okular without any other errors like this.
