### ISSUE TITLE
[BUG] Krusader not able to list files - currently unusable

### ISSUE THREAD

**Issue by bmihaila** [KDE-mac/homebrew-kde#330]
# Please specify exact formula that has issue

krusader-2.7.2_1

# What happened (include command output)

Krusader is not able to list any directory due to failing to load `kio`. When starting the application it will look like this:
<img width="1304" alt="Screenshot 2020-01-25 at 13 29 33" src="https://user-images.githubusercontent.com/2682197/73180736-9605ac80-411e-11ea-8f82-fa2b3fdd5181.png">
A similar issue appears when trying different `kio` protocols like trash:, sftp: or others. So basically krusader is not functional at the moment as one cannot do much without the files list. This is weird because Dolphin works just fine out of the box and all `kio` protocols there work.
Comparing the Krusader build formula to Dolphin did not give any further hints at the moment why Dolphin works and Krusader not. When starting Dolphin one can see it spawning a couple of processes of `kioslave5` whereas no such thing for Krusader. So Krusader seems to not be able to find or start those for some reason.

Has anyone managed to get Krusader working on Macos?

Bye
Bogdan

**Comment by yurikoles** [comment]
Hi, thanks for investigation!

Could you please try reverting this https://github.com/KDE-mac/homebrew-kde/pull/329?

Or maybe you didn't updated yet? I think this change is related somehow.

**Comment by bmihaila** [comment]
Hi @yurikoles 

Thanks for the fast answer. After some more digging into the issue and some DBus errors later I found the culprit. It seems I had a self compiled older build of Krusader around on the disk which for some reason got in the way when opening the Application as `open -a krusader` or via the launcher. That build had a broken kio. So all my bad :(. Opening the right Application by giving the full path and getting rid of the old one solved the above kio problem. User error in this case ;). Surprises me though how MacOS prioritizes some obscure build instead of taking the one from ~/Applications first.
Anyways, the issue did not have anything to do with above #329 commit - that is necessary.
Will close this issue, thanks.
