### ISSUE TITLE
[Feature Request] include kdialog install

### ISSUE THREAD

**Issue by time-killer-games** [KDE-mac/homebrew-kde#333]
Any plans to add kdialog to the list of applications that can be installed? I actually am relying on this for generating dialogs in one of my X11 projects and I'd like to give the developer an option to use either native Cocoa API for Objective C projects, or GTK+ and KDE for XQuartz-dependent C++ ports, depending on what their project needs are. There is a tap for Zenity by the GNOME developers, so I have Cocoa and GTK+ covered, now I just need Qt/KDE XQuartz support.

Mac's X11 Window System does not include the _NET_ACTIVE_WINDOW hint, which my project relies on to get the dialog window id. Zenity has no other way to do this because it can't print the Window ID, but KDialog can do this, so KDialog is largely preferred to have as an option because Zenity is kinda broken due to the lack of this Window Manager Hint present in XQuartz.

Thanks!
Samuel

**Comment by yurikoles** [comment]
@time-killer-games 333-get :)

**Comment by time-killer-games** [comment]
Thank you! Wow! That was pretty stinkin' fast!

**Comment by yurikoles** [comment]
You are welcome. Sponsor button is on top :)
