### ISSUE TITLE
[kmymoney] Dependencies missing

### ISSUE THREAD

**Issue by urban-1** [KDE-mac/homebrew-kde#334]
While installing  kmymoney, hit issues in `KDE-mac/kde/libalkimia` which was unable to find some required packages. The following seems to have fixed the issue:

```
brew install kde-mac/kde/kf5-knewstuff
brew install kde-mac/kde/kf5-plasma-framework
brew install kde-mac/kde/kf5-kdelibs4support
```

I also run `$(brew --repo kde-mac/kde)/tools/do-caveats.sh` few times in between of installs (not sure if it made any difference but thats what was suggested)

Raising this just for visibility, feel free to close if duplicate or not enough info :)

Cheers

(PS: I will be installing kmymoney and testing later today since it is still compiling it... )

**Comment by yurikoles** [comment]
Hi @urban-1!

This is very strange, because of brew sandbox, only those dependencies that you explicitly state in the formula are exposed to it. Did you modify formula file as well?

**Comment by urban-1** [comment]
Hi @yurikoles 

I have not modified the formula. While installing, I was getting an error that was looking for knewstuff config. I installed this by hand but then I got similar errors for plasma-framework. 

Eventually, kmymoney was installed but it cannot open any files. The error I get is "Could not read your data source. Please check the KMyMoney settings that the necessary plugin is enabled".

I can try to reproduce this by removing and reinstalling and this time keep the logs, however, last time I was compiling stuff for a day. At the end I installed a dmg from kde Jenkins which kinda works (is missing all icons but the rest seem ok - last successful build is old too: Dec 11)
