### ISSUE TITLE
[BUG] kf5-kdelibs4support Could not locate service type file kservicetypes5/kdedmodule.desktop

### ISSUE THREAD

**Issue by ivica-k** [KDE-mac/homebrew-kde#335]
# Please specify exact formula that has issue

KDE-mac/kde/kf5-kdelibs4support

# What happened (include command output)

==> Installing kde-mac/kde/dolphin dependency: KDE-mac/kde/kf5-kdelibs4support
Warning: Your Xcode (11.2.1) is outdated.
Please update to Xcode 11.3 (or delete it).
Xcode can be updated from the App Store.

==> Downloading https://download.kde.org/stable/frameworks/5.68/portingAids/kdelibs4support-5.68.0.tar.xz
==> Downloading from http://ftp.nluug.nl/pub/windowing/kde/stable/frameworks/5.68/portingAids/kdelibs4support-5.68.0.tar.xz
######################################################################## 100.0%
==> Patching
patching file cmake/FindDocBookXML4.cmake
==> cmake -G Ninja .. -DBUILD_TESTING=OFF -DKDE_INSTALL_QMLDIR=lib/qt5/qml -DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins -DKDE_INSTALL_QTPLUGINDIR=lib/qt5/p
==> ninja
Last 15 lines from /Users/ivica.kolenkas/Library/Logs/Homebrew/kf5-kdelibs4support/02.ninja:
[205/249] Building CXX object src/CMakeFiles/KF5KDELibs4Support.dir/kdeui/kprogressdialog.cpp.o
[206/249] Building CXX object src/CMakeFiles/KF5KDELibs4Support.dir/kio/kfileshare.cpp.o
[207/249] Building CXX object src/CMakeFiles/KF5KDELibs4Support.dir/kio/passworddialog.cpp.o
[208/249] Linking CXX shared library bin/libKF5KDELibs4Support.5.68.0.dylib
[209/249] Creating library symlink bin/libKF5KDELibs4Support.5.dylib bin/libKF5KDELibs4Support.dylib
[210/249] Generating networkstatus.json
FAILED: src/solid-networkstatus/kded/networkstatus.json
cd /tmp/kf5-kdelibs4support-20200320-67225-asle4s/kdelibs4support-5.68.0/src/solid-networkstatus/kded && /usr/local/bin/desktoptojson -i networkstatus.desktop -o /tmp/kf5-kdelibs4support-20200320-67225-asle4s/kdelibs4support-5.68.0/build/src/solid-networkstatus/kded/networkstatus.json -s kdedmodule.desktop
Warning: Could not locate service type file kservicetypes5/kdedmodule.desktop, tried ("/Users/ivica.kolenkas/Library/Application Support", "/Library/Application Support") and ":/kservicetypes5/kdedmodule.desktop" ((null):0, (null))
About to parse service type file "kdedmodule.desktop"
[211/249] Automatic MOC for target kf5deprecatedwidgets
[212/249] Automatic MOC for target kio_metainfo
[213/249] Automatic MOC for target kf5-config
[214/249] Automatic MOC for target kdebugdialog5
ninja: build stopped: subcommand failed.

**Comment by yurikoles** [comment]
Hi @ivica-k,

Thanks for report. Had your run this command before installing? `"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"`. This command is inside README of the repo.

**Comment by ivica-k** [comment]
Hey @yurikoles 

thanks for being very prompt in replying. I've seen that message multiple times but I was under the impressions that it should be executed after `dolphin` installation finishes.

Ran it just now and it fixed my immediate problem - thank you again.

**Comment by yurikoles** [comment]
You are welcome :)
