### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by learner-kde2020** [KDE-mac/homebrew-kde#341]
#Exact formula that has issue

kdevelop from kde-mac/kde

# What happened

Last 15 lines from /Users/mac/Library/Logs/Homebrew/kdevelop-pg-qt/02.ninja:
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../kdev-pg/kdev-pg-regexp.cpp:44:23: note: expanded from macro 'q_Hash_to_tr1_hash'
    template<> struct hash< type >                          \
                      ^~~~~~~~~~~~
/usr/local/opt/qt/include/QtCore/qhashfunctions.h:209:1: note: previous definition is here
QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF(QBitArray)
^
/usr/local/opt/qt/include/QtCore/qhashfunctions.h:200:5: note: expanded from macro 'QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF'
    QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH(Class, const argument_type &)
    ^
/usr/local/opt/qt/include/QtCore/qhashfunctions.h:180:16: note: expanded from macro 'QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH'
        struct hash< QT_PREPEND_NAMESPACE(Class) > {                \
               ^
1 error generated.

<details>
  <summary>/usr/local/opt/qt/include/QtCore/qhashfunctions.h:180:16: note: expanded from macro 'QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH'
        struct hash< QT_PREPEND_NAMESPACE(Class) > {                \
               ^
1 error generated.
ninja: build stopped: subcommand failed.</summary>

</details>

**Comment by learner-kde2020** [comment]
I think I made mistakes in reporting this issue. I apologise. I am still learner. 

This error appeared when I tried to install kdevelop on Mac High Sierra. 

Thank you for your help.

**Comment by yurikoles** [comment]
fixed in b311e83700aeae336f9e20b1902f5c2e4f850162
