### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by caduqued** [KDE-mac/homebrew-kde#342]
Trying to get Okular installed in MAC (OS X Catalina), and following instructions outlined in https://news.ycombinator.com/item?id=19494107, I get the error mentioned in the subject:

ninja: build stopped: subcommand failed.

Complete message is

`cmake -G Ninja .. -DBUILD_TESTING=OFF -DBUILD_QCH=ON -DKDE_INSTALL_QMLDIR=lib/qt5/qml -DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins -DKDE_INSTALL_QTPLUGINDIR=lib/qt5/plugins -
==> ninja
Last 15 lines from /Users/carlosduquedaza/Library/Logs/Homebrew/kf5-ki18n/02.ninja:
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr/scripts/ki18n5/trapnakron.pmap DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@ijekavian/scripts/ki18n5/ki18n5.js DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavian/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@ijekavian/scripts/ki18n5/trapnakron.pmap DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavian/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@ijekavianlatin/scripts/ki18n5/ki18n5.js DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavianlatin/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@ijekavianlatin/scripts/ki18n5/trapnakron.pmap DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavianlatin/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@latin/scripts/ki18n5/ki18n5.js DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@latin/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/sr@latin/scripts/ki18n5/trapnakron.pmap DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@latin/LC_SCRIPTS/ki18n5
-- copying... /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/po/uk/scripts/ki18n5/ki18n5.js DESTINATION /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/uk/LC_SCRIPTS/ki18n5
-- building... fi/scripts/ki18n5/general.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/fi/LC_SCRIPTS/ki18n5/general.pmapc
-- building... nn/scripts/ki18n5/skjermelement.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/nn/LC_SCRIPTS/ki18n5/skjermelement.pmapc
-- building... sr/scripts/ki18n5/trapnakron.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr/LC_SCRIPTS/ki18n5/trapnakron.pmapc
-- building... sr@ijekavian/scripts/ki18n5/trapnakron.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavian/LC_SCRIPTS/ki18n5/trapnakron.pmapc
-- building... sr@ijekavianlatin/scripts/ki18n5/trapnakron.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@ijekavianlatin/LC_SCRIPTS/ki18n5/trapnakron.pmapc
-- building... sr@latin/scripts/ki18n5/trapnakron.pmap to /tmp/kf5-ki18n-20200507-75723-1v62dvm/ki18n-5.69.0/build/locale/sr@latin/LC_SCRIPTS/ki18n5/trapnakron.pmapc
ninja: build stopped: subcommand failed.`

How can I get okular to get compiled?

**Comment by yurikoles** [comment]
Please follow the issue template.

**Comment by yurikoles** [comment]
And install instructions from README file, `cpanminus` way doesn't work now. Please invoke:
```
"$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
```
Before installing anything from this repo.
