### ISSUE TITLE
Error while installing kf5-phonon

### ISSUE THREAD

**Issue by hkumar6** [KDE-mac/homebrew-kde#74]
While installing `kf5-kate` which subsequently depends on `kf5-phonon`, the following error is thrown. Looks like the pulseaudio development files are missing, is it?

`/tmp/kf5-phonon-20170109-91372-pz577/phonon-4.7.1/phonon/pulsesupport.cpp:36:10: fatal error: 'pulse/glib-mainloop.h' file not found`

**Comment by sl1pkn07** [comment]
fixed in https://github.com/KDE-mac/homebrew-kde/blob/master/phonon.rb (?)
