### ISSUE TITLE
Issue of qt5 with qtwebkit

### ISSUE THREAD

**Issue by nigehban** [KDE-mac/homebrew-kde#82]
whenever I try to install kdevelop from your repo, it asks me first compile qt5 (5.8) with qtwebkit option enabled which takes ages in my laptop. It might be irrelevant to ask you but, is there any shorter method on brew to install qt5 with qtwebkit in mac ? Official qt web page says webkit was replaced with webengine module. 
<img width="574" alt="screen shot 2017-02-09 at 5 25 05 pm" src="https://cloud.githubusercontent.com/assets/15114973/22787288/6e8457fe-eee4-11e6-8ee4-60a54b32f8b1.png">
Thanks!

**Comment by franklinyu** [comment]
I'm interested in this issue, but I'm not familiar with KDE or Qt. Qt WebEngine is not documented very well:
1. [Qt WebKit page](https://wiki.qt.io/Qt_WebKit) does not even mention Qt WebEngine.
2. [Qt WebEngine page](https://wiki.qt.io/QtWebEngine) does not mention [*How to Try QtWebEngine*](https://wiki.qt.io/How_to_Try_QtWebEngine) or [*Porting from QtWebKit to QtWebEngine*](https://wiki.qt.io/Porting_from_QtWebKit_to_QtWebEngine).

Although KDevelop seems to [have switched from Qt WebKit to Qt WebEngine](https://phabricator.kde.org/R32:8a1536caf85f402d6d1c2d6cb00b0b94d34196bb), to me Qt WebEngine seems to be in early stage. In addition, I believe the change should first take place on [Homebrew Core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb) before we pick it up here.
